### ISSUE TITLE
[wekan] an extra file has to be deleted

### ISSUE THREAD

**Issue by brmvnml** [Uberspace/lab#1019]
I hope i'm doing this right...

an extra file has to be deleted before `npm install node-gyp node-pre-gyp fibers`

I had to delete ` rm ~/bundle/programs/server/node_modules/chalk/node_modules/.bin/strip-ansi` I don't think you mentioned it in the documentation, maybe you could add it in "the Install server" section? unless I did something wrong ofcourse..

---Off topic
Hey first of all thanks for the great guide, i managed to set everything up and it works! Magical!
Thank you for your work i really appreciate it

**Comment by pascoda** [comment]
as the guide has not been working for quite some time (see #1095), it has been removed, thus resolving this issue.
