### ISSUE TITLE
add guide_simpleID

### ISSUE THREAD

**Issue by 927589452** [Uberspace/lab#104]
Add a guide  for the openID provider simpleID

**Comment by 927589452** [comment]
i wanted to use xrds and havethe following error

**Comment by 927589452** [comment]
ok so still not working with a" Die übergebene OpenID konnte nicht überprüft werden. " 

there is somethingwrongwith mysetup 

ifanyone elsewantsto do the guide , better start from zero

**Comment by nichtmax** [comment]
@927589452 tbh I have no idea ☺️ Maybe ask our friends at hallo@uberspace.de if they can help you with your question. I don't think an issue in the lab is the right place to discuss it. And the link seems to be broken.

**Comment by ultrara1n** [comment]
I've SimpleID working for 3 years, first on U6 and then without a problem on an U7 space. Will have a look at creating a guide.

**Comment by ultrara1n** [comment]
Nearly finished, but i'm not quite happy with the configuration part yet
https://github.com/ultrara1n/lab/blob/master/source/guide_simpleid.rst
