### ISSUE TITLE
contribution not possible on non-Unix devices?

### ISSUE THREAD

**Issue by franok** [Uberspace/lab#1059]
# development instructions: link virtualenv documentation #activate-script

~It was just a minute of searching the web (or looking onto the `.venv/` directory), but would be nice if the [virtualenv documentation](https://virtualenv.pypa.io/en/legacy/userguide.html#activate-script) was linked in the readme section # development, pointing out that the `activate` script is located in another location on different OS.~
~This would help people who are less familiar with python and terminals.~

From the docs:
> On Windows, the equivalent activate script is in the Scripts folder:
> `> \path\to\env\Scripts\activate`

<br>

**EDIT**: I just found that contributing requires commands like `make`. **Seems like contributing from a Windows machine is not recommended?** Although most people here probably primarely use a UNIX-like system, I still think that would be worth a mention. I'm switching over to manjaro now 😄

**Comment by franok** [comment]
Note: There is make for windows (https://github.com/mbuilov/gnumake-windows), but probably nobody's first choice, who has access to a OS with package manager 😅

**Comment by luto** [comment]
> Seems like contributing from a Windows machine is not recommended?

I'd say "you're on your own", yes. None of the maintainers use Windows, so there are no instructions to do so. There is a [`make.bat`](https://github.com/Uberspace/lab/blob/main/make.bat) file that _should_ work, but I never tested it. Sorry :/
