### ISSUE TITLE
[jenkins] guide is broken

### ISSUE THREAD

**Issue by schneider-de-com** [Uberspace/lab#1098]
The guide for Jenkins does not work anymore. **Jenkins does not run with Java version 16.** We added a banner to the guide to signal the broken state.

If you have any insights, please comment on this issue. Pull requests fixing the guide are also highly appreciated. If the guide does not get fixed within two months, we will remove it from the lab, as documented in the [broken guides policy](https://github.com/Uberspace/lab/blob/main/BROKEN_GUIDES.md).

`WARNING: Running with Java class version 60 which is not in the list of supported versions: [52, 55]. Argument --enable-future-java is set, so will continue. See https://jenkins.io/redirect/java-support/`

@Snapstromegon FYI.

**Comment by Snapstromegon** [comment]
It seems like all current Jenkins versions are incompatible with openjdk 16. I recommend removing the guide for now. I might bring it back when Jenkins decides to upgrade to Java 16.

**Comment by gueldenstone** [comment]
What about just downloading jdk-11 from here: https://jdk.java.net/java-se-ri/11 and use that version to run jenkins.war?

**Comment by Snapstromegon** [comment]
Yes, this would probably be possible, but I wouldn't want to put this in the guide.
I still hope that Jenkins adds support for newer java versions.

**Comment by patient-developer** [comment]
Hi,
with the latest Regular Release war-file from Jenkins, i.e., [2.322](https://get.jenkins.io/war/2.322/jenkins.war) I can follow the guide for Jenkins working together with the currently installed openjdk 17.

**Comment by noave** [comment]
so can you confirm, that the guide works again with openjdk 17 ?
