### ISSUE TITLE
Change project name to lab in config

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/lab#11]

**Comment by luto** [comment]
the name is currently `Uberspace 7 Lab`. You would like it to be just `Lab`?

**Comment by nichtmax** [comment]
I mean "Manual" in particular.

<img width="756" alt="screen shot 2018-03-29 at 16 22 54" src="https://user-images.githubusercontent.com/988418/38094203-771a4b52-336d-11e8-9a98-3d00724fbfda.png">
