### ISSUE TITLE
add a guide for Matomo (previously known as Piwik)

### ISSUE THREAD

**Issue by GiantCrocodile** [Uberspace/lab#110]
Hello,

I just create this issue as a reminder that it would be nice to have a Matomo (previously known as Piwik) guide. I'm only experienced with old Piwik setups, so I can't write a guide for Matomo yet. I will try to check this out when I found a weekend with some spare time :).

Link to Matomo: https://matomo.org/
Installation guide: https://matomo.org/docs/installation/

**Comment by coderkun** [comment]
If I remember correctly, I simply downloaded and extracted the Matomo files to a sub-domain folder and entered the sub-domain in the browser. But I can test that and create a simple manual.

**Comment by GodMod** [comment]
I have added a guide for Matomo as Pull Request #120

**Comment by GiantCrocodile** [comment]
Thanks @GodMod!
