### ISSUE TITLE
[minim] guide is incomplete

### ISSUE THREAD

**Issue by pascoda** [Uberspace/lab#1106]
When following the guide, it breaks at "finish installation" - pointing the browser to my uberspace domain returns the nocontent.html page, as the minim installation is located in `~/html/minim`.

IMO there needs to be either 
* clarification to access the installation via `isabell.uber.space/minim`, or
* information on how to move the installation to `~/html`in order to access it via isabell.uber.space

**Comment by noave** [comment]
guides should always provide installation within `~/html` unless there are very specific reasons not to do that

**Comment by luto** [comment]
#1138
