### ISSUE TITLE
nextcloud recommends using PHP 8.0

### ISSUE THREAD

**Issue by Thorgrimson** [Uberspace/lab#1114]
https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html

**Comment by EV21** [comment]
Thank you for the news. 
PHPUnit tests for PHP8 nextcloud/server@cab44b6311d9ea51ac33e1382e65ddd0bedd95e1 
haven't made it to a release version yet, so it looks like it will only take effect for the latest development version >=23. I think if they don't backport that change soon we will just wait for NC23 to be released until we change the lab guide.
