### ISSUE TITLE
[guide] for antragsgruen

### ISSUE THREAD

**Issue by Thorgrimson** [Uberspace/lab#1127]
I just installed antragsgruen on an uberspace. Dont know if its worth writing a guide for it? Its just about putting the release files in document root.
https://motion.tools/

**Comment by SalocinHB** [comment]
Sure, go for it!

**Comment by errotu** [comment]
I followed the guide but was not able to get it successfully running. While the installation wizard works fine, when I save the configuration at the end I receive a 500 error. Now, when I access the website, it's only a "Not found: The requested URL was not found on this server." message. Do you have any idea how to fix this? I'm asking here as my guess would be that it's somehow uberspace specific and not a general problem with Antragsgrün.

**Comment by errotu** [comment]
Fyi: It seems to be only a problem with newer versions of Antragsgrün. I was able to successfully install v4.9.1 (but no newer version) and to upgrade to v4.12.0 step-by-step via the internal web updater (important: I had to execute the database migration after every single update step, not only once after all the file updates are completed).
