### ISSUE TITLE
[minim] update/improve guide

### ISSUE THREAD

**Issue by pascoda** [Uberspace/lab#1138]
checked guide on uberspace 7.11.5, with PHP 7.4 and minim 0.96

basically the installation guide still works. I just have two recommendations to improve/update the guide:
* the installation path is `…/html/minim`, so the domain to access it is `isabell.uber.space/minim` -- I recommend to rewrite the guide such that `isabell.uber.space` is the domain that serves the content.
* bit more explanation concerning themes would be nice (could also be a link to the appropriate part of the minim documentation), currently it only says "Create your own theme in minim/themes. Just copy the default theme or create one from scratch.".

hope you have the time, @minim-one  :)

**Comment by luto** [comment]
#1428
