### ISSUE TITLE
[jellyfin] add new guide for Jellyfin

### ISSUE THREAD

**Issue by knhash** [Uberspace/lab#1139]
I have tried out [Jellyfin](https://jellyfin.org/) on Uberspace and it works quite well. I intend to write a guide for it.

**Comment by nichtmax** [comment]
I'm not sure this is well suited for shared hosting since Jellyfin transcodes media and that's _very_ CPU heavy work... Do you have a demo installation on Uberspace? if so could you please hit is up via hallo@uberspace.de so we can have a look?

**Comment by nichtmax** [comment]
Unfortunately that's too much CPU for shared hosting 😞
![CPU graph](https://user-images.githubusercontent.com/988418/142010076-c42dad0e-4caf-4c1f-b737-29fad4d34835.png)

**Comment by nichtmax** [comment]
When there is an option to limit the threads feel free to write the guide ☺️

**Comment by knhash** [comment]
![image](https://user-images.githubusercontent.com/8710439/142182513-5c1ce9a2-8d68-4090-afe5-a78541f9a6e5.png)
With the option to set the thread to just one, the cpu utilitization stays around 5%. I did not see any noticable drop in quality while streaming.

**Comment by knhash** [comment]
PR raised here: https://github.com/Uberspace/lab/pull/1140

**Comment by knhash** [comment]
Guide published 😃
