### ISSUE TITLE
[vaultwarden] update section needs to be improved

### ISSUE THREAD

**Issue by noave** [Uberspace/lab#1164]
It looks like there is a problem while upgrading and compiling vaultwarden with a newer rustc version than used in the initial install. It looks like the info in `~/vaultwarden/target/.rustc_info.json` will be outdated then. There could be other problems with cached files, so we should check how to to a fresh update process here.

Moreover, there is a problem with the current folder names shown in the guide:
![image](https://user-images.githubusercontent.com/70973333/146017414-b9dbd913-e7ce-459d-81e2-8938eb99b2e2.png)

also the line `wget new-release.tar.gz` should be improved to show better how to download the new source

**Comment by noave** [comment]
@pxlfrk as the original author maybe you are interested in checking this out :-)

**Comment by pxlfrk** [comment]
@noave feel free to dive in & submit a PR for this. I'm quite busy & won't find time in the next few weeks. However we should investigate if it's a possible workarround to extract the prebuilt-binaries from the images (see [reference here](https://github.com/Uberspace/lab/issues/708#issuecomment-980531857)) - this would eliminate most of the problems occuring from this guide.

**Comment by knhash** [comment]
I have taken the liberty of raising a [PR with the changes to use pre-built binaries](https://github.com/Uberspace/lab/pull/1170). Please have a check if this works, @noave @pxlfrk

**Comment by pxlfrk** [comment]
Look's good, thanks @knhash for raising the PR! Didn't found any issues or errors while testing. From my side free to merge #1170.
