### ISSUE TITLE
[monica] new guide

### ISSUE THREAD

**Issue by wysiib** [Uberspace/lab#1173]
I'm working on a guide for [Monica](https://www.monicahq.com), an open source personal CRM (i.e., a tool to keep track of friendships and relations the same way a regular CRM does for customer relations).

**Comment by vat3r** [comment]
Hi Sebastian,
I tried to install it but got an error message after step:

`$ php artisan setup:production -v`

`In Connection.php line 703: SQLSTATE[HY000] [1045] Access denied for user '$user'@'$user.local.uberspace.de' (using password: YES) (SQL: select * from information_schema.tables where table_schema = $user_monica and table_name = cache and table_type = 'BASE TABLE')`

`In Connector.php line 70: SQLSTATE[HY000] [1045] Access denied for user '$user'@'$user.local.uberspace.de' (using password: YES)`

I wonder why the access should go via $user.local.uberspace.de. Do you have any idea?

**Comment by wysiib** [comment]
Hi Heiner,

sounds like there is something wrong with your database settings in `.env`.
Check the variables `DB_DATABASE`(should be your newly created database or the one with the same name as your account`, `DB_USERNAME` (should be the same as your account name) and `DB_PASSWORD`.

Afaik, the other variables can remain unchanged. I think the difference might be `DB_HOST=127.0.0.1`, i.e., I connect via localhost, not via `$user.local.uberspace.de`.

**Comment by vat3r** [comment]
> sounds like there is something wrong with your database settings in `.env`. Check the variables `DB_DATABASE`(should be your newly created database or the one with the same name as your account`, `DB_USERNAME`(should be the same as your account name) and`DB_PASSWORD`.

aaaaah, rookie mistake. At the beginning of the password there is a comma, which I overlooked when copying. Thanks for the hint to take another closer look! Best regards, Heiner
