### ISSUE TITLE
Adapt udocker installation part @ LibreOffice Guide 

### ISSUE THREAD

**Issue by therealsimwoe** [Uberspace/lab#1178]
In the guide for the [Libreoffice Installation](https://lab.uberspace.de/guide_libreoffice.html) the installation of udocker is explained as follows:

`curl https://raw.githubusercontent.com/indigo-dc/udocker/master/udocker.py > $HOME/bin/udocker`

The udocker.py file does not exist anymore in this project so above request will fail. I assume the installation procedure of udocker has been adapted. As far as I can see here: https://indigo-dc.github.io/udocker/installation_manual.html it is proposed as follows:

`curl -L https://github.com/indigo-dc/udocker/releases/download/v1.3.1/udocker-1.3.1.tar.gz > udocker-1.3.1.tar.gz`
`tar zxvf udocker-1.3.1.tar.gz`
```export PATH=`pwd`/udocker:$PATH```

I tried this out in $HOME/bin/ and it works perfectly fine. The only thing I needed to additionally change was in the libreoffice.ini file.
Here I had to change:
command=bash -c '\
    %(ENV_HOME)s/bin/udocker run \

to:
command=bash -c '\
    %(ENV_HOME)s/bin/udocker/**udocker** run \ 

Since the udocker file is after following above procedure contained within the udocker folder.

Everything else worked perfectly fine!

Since in my opinion a new version of this guide makes sense since the current one is not working anymore due to the initial not working curl request I am proposing this here... Hope that is fine :)

//cc @jorsn

**Comment by jorsn** [comment]
Thanks! I'll fix it.
