### ISSUE TITLE
[listmonk] adding a new guide

### ISSUE THREAD

**Issue by knhash** [Uberspace/lab#1190]
I would like to create a new guide for [listmonk](https://listmonk.app). It is a self-hosted newsletter and mailing list manager written in Go. It is fast, feature-rich, and packed into a single binary, linked to a PostgreSQL. 

It is a sufficently easy install, and I will write guide for it if there is an interest for it.

**Comment by jfilter** [comment]
There is already a guide for listmonk: https://lab.uberspace.de/guide_listmonk/

**Comment by knhash** [comment]
Oh wow. This is embarrassing, I don’t know how I missed it. 

Closing this issue. Apologies.
