### ISSUE TITLE
[libreoffice] guide broken

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/lab#1192]
udocker URL does not work anymore

the more severe thing is that the path `https://xxx/loleaflet/dist/admin/admin.html` does not work.

**Comment by nichtmax** [comment]
@jorsn any chance you can have a look?

**Comment by jorsn** [comment]
udocker part is #1178.

Does libreoffice run correctly (test e.g. with `curl -k https://isabell.uber.space` as in [the guide](https://lab.uberspace.de/guide_libreoffice.html#test-and-use-the-service))?

If it runs, does `https://xxx/browser/dist/admin/admin.html` work? I see they changed `loleaflet` to `browser` and `loolwsd` to `coolwsd`, for collabora. For plain libreoffice I have to have a look.

**Comment by BabyFnord** [comment]
Hello @jorsn,
I reported this to Uberspace support a few days ago, having followed the steps as per your manual (thank you for that 🙂).
`curl -k https://domain.my` returns `OK`, yet pointing any browser there leads to either downloading a file titled `domain.my` containing `OK`, or just displaying `OK`.

> If it runs, does `https://xxx/browser/dist/admin/admin.html` work? I
Yes, this renders (only) the admin console accessible.

**Comment by jorsn** [comment]
> For plain libreoffice I have to have another look.

Plain libreoffice is officieally “frozen” and not updated for 1.5 years. Hence, I have concentrated the guid on CODE, now. I will push it when I've fixed the udocker install.

**Comment by jorsn** [comment]
> Yes, that renders (only) the admin console accessible.
  -- @BabyFnord 

Should it do more? Or does everything work, now?

**Comment by BabyFnord** [comment]
@jorsn, this is my issue, following your manual:
> `curl -k https://sub.domain.my` returns `OK`, yet pointing any browser there leads to either downloading a file titled `sub.domain.my` containing `OK`, or just displaying `OK`. EDIT needed to clarify it's a subdomain.

The only difference is, I've set `uberspace web backend set sub.domain.my --http --port 9980` to access Libre Office Online via that subdomain. The installation is inaccessible via `sub.domain.my`, I only get either a blank page displaying `OK` or that file as described above 🤷🏻‍♂️. Neither me nor Uberspace support know how to fix this 🤔. My uneducated guess is, the web backend does not point to the landing page. Can you help, please?

**Comment by jorsn** [comment]
Ah, sorry, I didn't read properly.

What you describe is the intended behavior. The curl command is your browser: It sends an http request to the server and displays the response, only in the plain old terminal instead of the usual very fancy web user interface.

A landing page doesn't exist, and document-specific urls for embedding the editor in an iframe are negotiated between your embedding web app and libreoffice as described the [CODE manual](https://sdk.collaboraonline.com/docs/How_to_integrate.html#website-that-presents-the-editing-capabilities). You need a WOPI server serving the files to libreoffice anyway.

**Comment by BabyFnord** [comment]
Oh no, I thought implementing an existing (SaaS) NC account via WebDAV satisfies the storage needs of libreoffice, and libreoffice provides its own web app. WebDAV appears to be supported for storage, though. Please forgive my ignorance both @nichtmax and you, thanks a bunch for clarifying. I guess I'll have to give up using libreoffice Online for the time being.

**Comment by jorsn** [comment]
On your SaaS NC instance, you don't have NC admin access? If you have, then you can add the libreoffice app and configure it, but for the whole NC instance.

**Comment by jorsn** [comment]
Just put the NC in another uberspace for separation (see [blog](https://blog.uberspace.de/ein-bekenntnis-zur-freien-preiswahl-und-ein-aber/), section “Aber ihr habt doch gesagt…”). But now that the discussion about general general NC+Uberspace  becomes really off-topic, rather [email](mailto:johannes@jorsn.eu) me if you want to discuss.

**Comment by arkap** [comment]
I'm trying to use the libreoffice server at `docs.mydomain.com` with my self-hosted nextcloud. 
I've followed the guide and `curl -k https://docs.mydomain.com` checks out. My nextcloud instance is at `cloud.mydomain.com` which is what I've put into the udocker `fileserver` environment variable. From the nextcloud settings it seems that it connects to the document server correctly. However when I open a document in nextcloud it freezes and I see the following errors on my uberspace document server:
```
ERR  No acceptable WOPI hosts found matching the target host [cloud.mydomain.com] in config.| wsd/Storage.cpp:276
ERR  loading document exception: No acceptable WOPI hosts found matching the target host [cloud.mydomain.com] in config.| wsd/DocumentBroker.cpp:2091
```
Any ideas what might be the issue?

**Comment by BabyFnord** [comment]
Sounds familiar 👾. What does your `libreoffice.ini` look like? Here's a snippet courtesy of @jorsn, which brought my installation to life:
`command=bash -c '\
    %(ENV_HOME)s/bin/udocker run \
    --user="$(jq -r .container_config.User \
                 < %(ENV_HOME)s/.udocker/containers/"$container"/container.json)" \
    --env=DONT_GEN_SSL_CERT=1 \
    --workdir=/ \
    --env=username="$username" --env=password="$password" \
    --env=dictionaries="$dictionaries" \
  --env="extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:security.capabilities=false --o:storage.wopi.host[0]=$(echo "$fileserver" | sed "s/\./\\\\./g") $extra_params" \
    "$container" \
    '`

**Comment by arkap** [comment]
Yeah, that fixed it :)
I guess the problem was that my `libreoffice.ini` had this line as per the guide:
```
--env=domain="$(echo "$fileserver" | sed "s/\./\\\\./g")" \
```
while it has to be part of `extra_params` as `--o:storage.wopi.host[0]=$(echo "$fileserver" | sed "s/\./\\\\./g` as in your snippet.
Thanks!

**Comment by BabyFnord** [comment]
Cool, glad I could help 😊. 
Though the credits and Kudos for this go to @jorsn, who most patiently helped me in getting my installation to work.
