### ISSUE TITLE
[postgresql] createuser/createdb asks for password (v13)

### ISSUE THREAD

**Issue by ebroda** [Uberspace/lab#1193]
I was trying to install Focalboard and setting up postgresql therefore following the guide in the lab. I think I did all steps, but on ``createuser`` and ``createdb`` the command asks for another password, which is the one in ~/.pgpass, but somehow not read from there.

```shell
[myaccount@cepheus ~]$ uberspace tools version show postgresql
Using 'Postgresql' version: '13'
[myaccount@cepheus ~]$ createuser focalboard -P
Enter password for new role:
Enter it again:
Password:
[myaccount@cepheus ~]$ createdb --encoding=UTF8 --owner=myaccount --template=template0 focalboard
Password:
[myaccount@cepheus ~]$ 
```

Can someone confirm this behaviour? In case yes we might add at least a hint to the guide.
Or did I miss an aspect?

**Comment by nicogramm** [comment]
It's hard to comment on this without more information.
I can however confirm that I successfully setup postgresql and a user and database following the instructions in the lab.
Does your `~/.pgpass` file follow the format:
```
#hostname:port:database:username:password (min 64 characters)
*:*:*:<username>:1234567890123456789012345678901234567890123456789012345678901234
```
That was where I messed up yesterday before fixing it and then being successful.

**Comment by ebroda** [comment]
I just followed the steps of the guide again on a fresh uberspace and now it worked fine. I couldn't reproduce my errors. Therefore I think I missed something in my first try. So the guide is fine and I'll close this issue. Sorry for the trouble :)
