### ISSUE TITLE
[CryptPad] broken after update to version 4.13.0

### ISSUE THREAD

**Issue by 23n** [Uberspace/lab#1242]
After update to version 4.13.0 CryptPad drive doesn't get loaded, stucks.
![CryptPad 2022-03-31 21-46-41](https://user-images.githubusercontent.com/1303101/161136878-8a81e8fd-4ecb-4b03-a024-a5eb5244ae06.jpg)

I found this older issue, but I'm not sure if the two have anything to do with each other:
https://github.com/xwiki-labs/cryptpad/issues/382

**Comment by noave** [comment]
I could install the most recent version 4.14.0 on a fresh uberspace, but I had to keep the current node version 16, I will remove the advise to downgrade to node 12 as stated in the guide.

Can you try updating with updating the node version?

**Comment by 23n** [comment]
After updating to node 16 and cryptpad 14.4, I get a Javascript error:
This page can only be accessed via http://localhost:3000.
Strange. I'm back at version 13 for now.

**Comment by 23n** [comment]
Version 5.0.0. apparently fixes a lot of previous bugs. Also my described problem is solved, CryptPad runs again, or even better than ever.
