### ISSUE TITLE
Uberlab support policy and complex guides

### ISSUE THREAD

**Issue by jorsn** [Uberspace/lab#1249]
In https://github.com/Uberspace/lab/pull/1196#issuecomment-1103807417, @nichtmax announces that the LibreOffice guide might eventually be removed because it is complex and causes much support load. When I created the guide, it had been requested for long (#160), and I as the guide author didn't notice much support load, nor do I probably know what people have difficulties with.

If authors should improve their guides based on community feedback, maybe one could advertise more prominently that people create GitHub issues and include the guide authors in support requests.

What is the current support policy of the Uberlab?

> Feel free to ask our support for help when you’re stuck somewhere or have any questions.

it reads on https://lab.uberspace.de/. And:

> Everybody is welcome to contribute new guides, changes to existing ones, or even just a small issue to draw our attention to problems or missing guides. [...GitHub...]

This seems to put most of the support load on the shoulders of the Uberspace team, without the authors noticing, which is a problem especially for more complex guides that Uberspace maybe wouldn't want to support very intensively.

If such guides shouldn't be in the uberlab, maybe we could have a collection of links to such guides on external sites in the fashion of the former “cool” site of the old wiki, so that one could discover them easily?

What do you think?

**Comment by nichtmax** [comment]
> What is the current support policy of the Uberlab?

We see the lab as part of Uberspace and have the claim to support every guide in the support, therefore one of us goes through it completely before the merge and looks for pitfalls. As soon as an installation deviates from the guide - e.g. by a separate DocumentRoot and multiple applications on one account - the support ends.

> This seems to put most of the support load on the shoulders of the Uberspace team, without the authors noticing, which is a problem especially for more complex guides that Uberspace maybe wouldn't want to support very intensively.

Yes, that is so. But that's ok, we are paid for our work and can't and don't want to shift the responsibility to the authors of the guides.

> If such guides shouldn't be in the uberlab, maybe we could have a collection of links to such guides on external sites in the fashion of the former "cool" site of the old wiki, so that one could discover them easily?

The section in the wiki had the problem that many links did not work anymore with time and also the guides were not actively maintained. This is understandable, we can't expect that the guides are kept up to date and functional. And here we also have the problem that the users then expect support from us and are frustrated by broken guides and we can then do even less than if we had control over them by ourselves. 

These are exactly the factors that we had in mind when we developed the lab and why the lab looks the way it does today and why the rules are the way they are: We're doing a balancing act here and living compromise. Of course, as always, we are open to suggestions for improvement.
