### ISSUE TITLE
[focalboard] guide broken

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/lab#1256]
[t/sirlupus](https://twitter.com/sirlupus/status/1519702190117560322):
> Hallo @ubernauten , wollte nur Bescheid geben dass der Guide für Focalboard ( [lab.uberspace.de/guide_focalboa…](https://t.co/LVesPoirDD) ) nicht mehr zu passen scheint. Eine "focalboard-server" gibt es nicht mehr. Sprung von 0.6 auf 0.15 ist wohl zu hoch :)

**Comment by pascoda** [comment]
looks like they overhauled the folder structure. however, with some minor changes, I was able to set up the app. 
I'll update the guide accordingly.
