### ISSUE TITLE
[pixelfed] Guide broken (Problem with federation)

### ISSUE THREAD

**Issue by rickgardner077** [Uberspace/lab#1259]
Following the Uberspace guide to install pixelfed on U7 federation features are broken. Unable to open any remote profiles on other Fediverse installs inside pixelfed, unable to follow/like/comment from remote Fediverse instances. 

Following [pixelfed's own Generic Installation Guide](https://docs.pixelfed.org/running-pixelfed/installation.html#setting-up-services) I got federation features working.

The laravel log in my pixelfed installation reported this error:
`[2022-05-03 16:05:36] production.ERROR: Unable to read key from file file:///var/www/virtual/$USER/pixelfed/storage/oauth-public.key {"exception":"[object] (LogicException(code: 0): Unable to read key from file file:///var/www/virtual/$USER/pixelfed/storage/oauth-public.key at /var/www/virtual/$USER/pixelfed/vendor/league/oauth2-server/src/CryptKey.php:67)`

Adding the additional step `php artisan passport:install` Pixelfed can now talk to Mastodon on mastodon.social.

Terminal output:

```
[$USER@avior pixelfed]$ php artisan passport:install
Encryption keys generated successfully.
Personal access client created successfully.
Client ID: 1
Client secret: ***
Password grant client created successfully.
Client ID: 2
Client secret: ***
[$USER@avior pixelfed]$ php artisan config:clear
Configuration cache cleared!
[$USER@avior pixelfed]$ php artisan key:generate
**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? (yes/no) [no]:
> yes

Application key set successfully.
[$USER@avior pixelfed]$ php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!
[$USER@avior pixelfed]$
```

Persisting issue 1: Communication between Pixelfed and Pleroma not consistent (follow/like/comment work only intemittently). 
Persisting issue 2: Import feature from Instagram breaks on upload of file `media.json` with Internal Error 500

**Comment by taddydevil** [comment]
Hi! I wrote the guide long time ago. It was only a question of time until the guide didn't work cause pixelfed is in a fast developing state.
I'll investigate in this issue and update the guide asap. Thank you for the hint!

**Comment by rickgardner077** [comment]
I updated Pixelfed on U7 to v0.11.3, the issue with follows from Pleroma is resolved. Issue 2 not resolved: Import feature from Instagram breaks on upload of file media.json with Internal Error 500
