### ISSUE TITLE
gitea service fatal can't find command

### ISSUE THREAD

**Issue by twiebke** [Uberspace/lab#1267]
By exercising the guide, especially https://github.com/Uberspace/lab/blob/main/source/guide_gitea.rst#service-for-gitea  I get after 

`supervisorctl status`

`gitea                            BACKOFF   can't find command 'gitea'`

or

`gitea                            BACKOFF   can't find command 'gitea web'`

depends on gitea web or "gitea web" in ~/etc/services.d/gitea.ini

**Comment by EV21** [comment]
That probably means exactly what is says:
I could reproduce that by moving/renaming gitea
```
[isabell@stardust services.d]$ supervisorctl status gitea
gitea                            FATAL     can't find command 'gitea'
```

Does the binary exist at the following location?
`~/gitea/gitea`

If this is not the case you either need to change the service (ini) file or something went wrong by executing the following part:

```
[isabell@stardust ~]$ VERSION=1.16.8
[isabell@stardust ~]$ mkdir ~/gitea
[isabell@stardust ~]$ wget -O ~/gitea/gitea https://github.com/go-gitea/gitea/releases/download/v${VERSION}/gitea-${VERSION}-linux-amd64
[...]
Saving to: ‘/home/isabell/gitea/gitea’

100%[========================================================>] 83,243,800  14.9MB/s   in 9.8s

2020-06-01 21:00:42 (8.11 MB/s) - ‘/home/isabell/gitea/gitea’ saved [83243800/83243800]
[isabell@stardust ~]$
```

```
[isabell@stardust ~]$ chmod u+x ~/gitea/gitea
```


Does your `~/etc/services.d/gitea.ini` file look exactly like this?
```ini
[program:gitea]
directory=%(ENV_HOME)s/gitea
command=gitea web
startsecs=30
stopsignal=HUP
autorestart=yes
```
If not, then change it, save it and then run
```
supervisorctl reread
supervisorctl update
supervisorctl status
```

**Comment by twiebke** [comment]
> Does the binary exist at the following location?
> ~/gitea/gitea
Yes and "~/gitea/gitea web" works well.

>  Does your ~/etc/services.d/gitea.ini file look exactly like this?
Yes, exactly. And I tried command="gitea web" as command=~/gitea/ "gitea web"

**Comment by twiebke** [comment]
Nico wrote it schould be:
`command=%(ENV_HOME)s/gitea/gitea web`

**Comment by SalocinHB** [comment]
Fixed in https://github.com/Uberspace/lab/commit/30a99dfbb07175a7581b7fdbbd27d614581b0098

**Comment by EV21** [comment]
Thank you for the info and sorry, that was my mistake. 😞 - In my setup I have a wrapper script at ~/bin/gitea that made the unreachable command reachable and I also changed too much in the guide with my last pull request here. - It is now fixed. Thank you @SalocinHB
