### ISSUE TITLE
[rocket chat] broken guide because of glibc

### ISSUE THREAD

**Issue by noave** [Uberspace/lab#1272]
The guide does no longer work with the current releases of rocket chat. It requires glibc2.25 which is not provided on CentOS7. It might be possible to rebuild the dependencies, see https://forums.rocket.chat/t/centos-7-install-errors/761/4

But for now the guide must be marked as broken, maybe you can help here out @d-sko as the original author of the guide?

**Comment by d-sko** [comment]
Hi, thanks for the information. I'll have a look later.

**Comment by d-sko** [comment]
Ok, so I finally got some time to look into this. It is possible to rebuild the `forked-matrix-sdk-crypto-nodejs`-dependency, which causes npm to fail, by installing rustup and a newer version of cmake, as described in an related Rocket.Chat-Issue: https://github.com/RocketChat/Rocket.Chat/issues/25396#issuecomment-1119036136 . But starting Rocket.Chat results in an immediate segmentation fault, without any prior output.

So while rebuilding with rustup might be a valid workaround to fix the initial problem (is it? I have absolutely no knowledge of rust, and when installing rustup it says I shouldn't install it along the "normal" rust-command), it just reveals the next error.

**Comment by olearytd** [comment]
Running into this same issue; able to rebuild the module with yarn but once I try to start the service I get the Segmentation Fault without much indication of the issue.

Any updates?

**Comment by d-sko** [comment]
Unfortunately I have no updates so far. I have not found a solution and it looks like others have problems with RC and Centos 7 as well. There are some issues (like the one I linked in my last comment) about problems with Centos 7, maybe we have to wait until the RC devs hopefully fix this. Until then the only workaround I see is installing an older release, but that's of course not a good one.
