### ISSUE TITLE
[nextcloud] manually upgrade from PHP 7.3

### ISSUE THREAD

**Issue by noave** [Uberspace/lab#1275]
On Uberspace we recently removed the outdated PHP version 7.3 which caused trouble for not updated Nextcloud versions below NC21. Because the automatic updater wont work without PHP 7.4 these steps show how to manually update your Nextcloud:

1. Login to your shell
https://lab.uberspace.de/howto_ssh/
3. Rename your current nextcloud folder _(your path may differ here, assuming `/var/www/virtual/$USER/html` for now )_
`mv /var/www/virtual/$USER/html /var/www/virtual/$USER/html.old` 
4. Recreate your nextcloud folder
`mkdir /var/www/virtual/$USER/html`
5. Go to this folder and download the following Nextcloud major version to yours, so if you are on NC20 then NC21:
`cd  /var/www/virtual/$USER/html`
`curl https://download.nextcloud.com/server/releases/nextcloud-21.0.0.tar.bz2 | tar -xjf - --strip-components=1`
6. Copy your old config file here
`cp /var/www/virtual/$USER/html.old/config/config.php  /var/www/virtual/$USER/html/config/`
7. Check if your file data storage is _inside_ the old nextcloud folder
`grep datadirectory  /var/www/virtual/$USER/html/config/config.php`
if so, copy or better move it as well
8. Run the upgrade command
`php occ upgrade`

From Nextcloud Version 21 on, the update script will work again with the current PHP versions (PHP 7.4 and higher). If you are on very outdated Nextcloud versions like NC18, you will have to do the manual upgrade described here for each version until NC21, so `NC18->NC19->NC20->NC21`

**Comment by EV21** [comment]
I think if you've already moved that directory (at 6.) it should look like this:
```diff
- grep datadirectory /var/www/virtual/$USER/html/config/config.php
+ grep datadirectory /var/www/virtual/$USER/html.old/config/config.php
```
- Do you think these manual steps should make their way back to the guide? - Maybe at the troubleshooting section?
- Perhaps we could add one more note: Nextcloud major releases are planned to be actively maintained for at least 8 months after their release, in reality it looks like about 1,5 years at maximum (support for the latest 3 major branches) see [Maintenance-and-Release-Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule). Staying productive with older releases to ensure the compatability to apps and costum adjustments is totally fine as long as you don't exceed the end of life.

**Comment by noave** [comment]
Some users have problems with Nextcloud which are older than NC18 because the manual update guide here wont work with them. In this case its probably necessary to migrate the Code/DB externally on a system with PHP 7.3 or to install NC new and import the files. Maybe someone else here has better solutions or can write guides for these cases. 

Discussion here is open for users who have these problems and users who might be able to help :-)
