### ISSUE TITLE
[cloudlog] Planned new guide

### ISSUE THREAD

**Issue by florianprischl** [Uberspace/lab#1285]
Cloudlog (GitHub: https://github.com/magicbug/Cloudlog/ Website: https://www.magicbug.co.uk/cloudlog/) is a self-hosted PHP application that allows logging of amateur radio contacts anywhere.

I have just installed Cloudlog on my uberspace and plan to eventually write a guide for installation. Installation is straightforward with one problem, which I could not quickly diagnose, but easily work around.

**Comment by SalocinHB** [comment]
@florianprischl did you make any progress writing the guide? If not, I'll give it a go.

**Comment by florianprischl** [comment]
Thanks so much, @SalocinHB! Sorry I stayed quiet.
