### ISSUE TITLE
add guide for partkeepr

### ISSUE THREAD

**Issue by 927589452** [Uberspace/lab#129]
partkeepr.org

**Comment by sunflower-seed** [comment]
I wrote the current guide in the Partkeepr Wiki. I'll have a look at it.

**Comment by sunflower-seed** [comment]
Unfortunately partkeepr requires php zend ldap module, which is currently not  installable.

**Comment by sunflower-seed** [comment]
**TL;DR:**

- ldap module landed in U7
- installation possible but when starting some issues coming up

Maybe some php / apcu expert wants dig into it?

Details:
It is possible to run PartKeepr setup. But you can't restart respective re-run ist, then the setup check fails.
The setup complains about missing apcu module, nevertheless it is available in U7. 
After starting the app you get an error like this: https://github.com/partkeepr/PartKeepr/issues/916

It seems that PartKeepr does not run with the apcu packages provided in CentOS.
(see: https://github.com/partkeepr/PartKeepr/issues/521 )

**Comment by luto** [comment]
partkeepr did not get a new release for three years and does not support non-EOLd PHP versions, so I don't see this happening at the moment. Feel free to reopen, should the project come back to life.
