### ISSUE TITLE
add a guide for Seafile

### ISSUE THREAD

**Issue by luto** [Uberspace/lab#133]
[Seafile](https://www.seafile.com) is a "cloud" storage solution like the self-hosted NextCloud or not-so-self-hosted Dropbox. Installation on uberspace differs from the official guide in some places (mostly dependencies).

**Comment by Finn0811** [comment]
I'm currently working on a seafile guide but I can't manage one of the last steps: Getting a .htaccess proxy running.

`DirectoryIndex disabled

RewriteEngine On
RewriteRule ^(.*) http://localhost:61360/$1 [P]`

This one leads to the following error:

>2018-10-04 18:49:41,165 [WARNING] django.security.csrf:160 _reject Forbidden (Referer checking failed - https://<user>.uber.space/accounts/login/?next=/ does not match any trusted origins.): /accounts/login/

After searching through some google results I'm almost sure the apache or nginx? proxy is missing the Host header? 
https://forum.seafile.com/t/solved-403-forbidden-after-upgrade-to-6-3-1/6525/7

Maybe someone has an idea to fix this 👍

**Comment by Finn0811** [comment]
I think this should be closed.. :)

**Comment by Stunkymonkey** [comment]
@luto there is already a guide for it.

**Comment by luto** [comment]
indeed. thanks!
