### ISSUE TITLE
add a guide for nagios

### ISSUE THREAD

**Issue by moschlar** [Uberspace/lab#136]
Nagios calls itself "The Industry Standard In IT Infrastructure Monitoring".

I'm currently testing the installation on an Uberspace 7 host and plan to write a guide for it.

**Comment by luto** [comment]
in my (personal) opinion, nagios is a little dated. I'd recommend icinga2 or even a more hipstery tool like prometheus, depending on the use case.

**Comment by moschlar** [comment]
But it's also the monitoring core for Check_MK, which I also wanted to evaluate. ;-)

**Comment by moschlar** [comment]
Since Check_MK won't run, I won't finish writing this...
