### ISSUE TITLE
[phpbb] check for php 8.0 compatibility

### ISSUE THREAD

**Issue by noave** [Uberspace/lab#1402]
PHP 7.4 will be EOL after November 28. We need to check if this guide will still work with PHP 8.0.

**Comment by EV21** [comment]
phpBB added `PHP 8.1` to their test matrix for `3.3.3` (the version used in this guide) - but PHP 7.4 is used here (it was actually to low when the guide was written)
phpBB added `PHP 8.2` to their test matrix for `3.3.6`

I am running a deactivated archive board with the latest `3.3.9` on Uberspace with `PHP 8.1` maybe just bump to that version

**Comment by kimdiallo** [comment]
closed by 4a68baa90857ee34364085e358c83c1354422800
