### ISSUE TITLE
add a guide for Mailman3

### ISSUE THREAD

**Issue by smokephil** [Uberspace/lab#141]
GNU Mailman is a computer software application from the GNU Project for managing electronic mailing lists. Mailman is coded primarily in Python and currently maintained by Abhilash Raj. Mailman is free software, licensed under the GNU General Public License.

http://docs.mailman3.org/en/latest/

**Comment by pheraph** [comment]
Would love a guide for a decent mailing list manager. Maybe this tutorial is a starting point? https://www.emptyweb.de/post/mailman-uberspace-tutorial/

**Comment by komaspieler** [comment]
@smokephil are you already working on this? I have just created a pull request for a Mailman 2.1 guide but haven't had much success installing Mailman 3 on Uberspace 7 yet. I'd be happy to give it a try.

**Comment by Pokerkoffer** [comment]
Mailman 3 needs WSGI (see http://www.list.org/requirements.html ).
WSGI is not supported on U6 (see https://wiki.uberspace.de/brainstorming )
Reading the arguments mentioned, i doubt that WSGI is supported in U7 (can't check this right now as i am not at home).

Has anyone found a replacement for wsgi yet?

**Comment by smokephil** [comment]
@komaspieler I haven't started working on it yet. If you want you can do it.

**Comment by jeyca** [comment]
I would be happy to have a guide for this. I just tried to install it a few days before, It was no problem to install the suite with postorious and so on, but could not get the core to work. I do not know how to configure the REST api to start it and make it available for the suite.

**Comment by luto** [comment]
WSGI is supported on both Uberspace 6 and 7, using an application server like [gunicorn](https://gunicorn.org/). Since mailman is just a pretty vanilla django app, it should work just fine in uberspace 6 and 7 :)

**Comment by komaspieler** [comment]
Thanks for the tip, @luto! @smokephil - sure, I'll get started before christmas, I think. If anybody wants to help or wants to beat me to it, let me know. I'll be working in [komaspieler/lab](https://github.com/komaspieler/lab).

**Comment by al-ion** [comment]
Hey @komaspieler any news here?

**Comment by komaspieler** [comment]
No, I haven't gotten around to it yet, unfortunately (thanks to the flu-season...).

**Comment by Pokerkoffer** [comment]
@komaspieler any updates?

**Comment by komaspieler** [comment]
Sadly, no. I have very little time at the moment to work on this.. if anyone wants to go for it, please don't wait for me.

**Comment by rikroe** [comment]
Hey guys, I have created a guide for Mailman 3 on U7. It's my first guide, so please forgive my errors :D
You can currently find it in  [rikroe/lab](https://github.com/rikroe/lab/blob/master/source/guide_mailman-3.rst). 

**Please beware,** I've not submitted a pull request yet due to the following issues:

- I have not tried the guide on a clean U7 yet. Will try to do this soon, just wanted to give you some hints
- Daemonizig mailman with supervisord does not work yet - there are big red error messages around that part. 

``mailman start`` starts a runner subprocess and then finishes gracefully so supervisord thinks it has stopped and tries again although its running. It maybe easy to fix but I am definitely not comfortable enough with that. So suggestions (or pull requests) are welcome :)

**Comment by ezzra** [comment]
wow thats a lot, looking forward to test this out soon!

**Comment by rikroe** [comment]
Hey all, just pushed a new version to my repo, containing a bash mapper to be able to daemonize mailman through supervisord.

So please feel free to use the guide, still need to double-test it on a clean uberspace though.

**Comment by nicostuhlfauth** [comment]
@rikroe One suggestion: Could you maybe add an additional chapter about how to upgrade from Mailman 2? So, especially interesting would be: How to transfer existing mailing lists? How to completely remove Mailman 2?

**Comment by luto** [comment]
@nicostuhlfauth there is [some information](http://docs.mailman3.org/en/latest/migration.html#upgrade-strategy) in the mailman docs. In any case, please open a separate issue for this, thanks :)

**Comment by nicostuhlfauth** [comment]
@luto Ok, I‘ll try to get it running and probably create a PR then.

**Comment by rikroe** [comment]
@nicostuhlfauth cool, that's great! Unfortunately I won't be any help - created the guide from scratch without any experience in Mailman 2 (so nothing to migrate).
Also please check the archiving part - it is installed but I didn't look into that much detail there either. My focus was on setting up an email distribution list.
