### ISSUE TITLE
[django] guide order of steps wrong

### ISSUE THREAD

**Issue by Marrin** [Uberspace/lab#1435]
The guide has `gunicorn` installation, configuration, and restart before installing Django and creating the project. This means the restart in the `gunicorn` section inevitable fails because it tries to use/serve the project which is created in the _next_ steps of the guide.

I am I bit unsure which is the better solution: taking the `gunicorn` configuration and restart and move it after the Django installation, or move the complete `gunicorn` section after the Django section.

**Comment by brutus** [comment]
I prefer moving the service setup with gunicorn to its section, after the Django one. Because I think the Django installation/setup and running it as a service (with gunicorn) are two separate steps.
