### ISSUE TITLE
[mailman3] Setup for subdomain?

### ISSUE THREAD

**Issue by tvogel** [Uberspace/lab#1453]
Hi!

Is it possible to set up mailman3 for a subdomain, i.e. `lists.isabell.uber.space`? That might reduce the trouble with setting up qmail-configuration because the super-domain could still handle ordinary email addresses and the lists-domain mailing lists only. 

Regards,

Tilman

**Comment by noave** [comment]
Of course that is possible and I would always encourage to do so. However, we always encourage to use one Uberspace for one app/project, so you should use one account for your mailinglists (with subdomain lists.example.com) and another account for ordinary mails
