### ISSUE TITLE
[Pixelfed] Picture upload result is just a placeholder since last update

### ISSUE THREAD

**Issue by 23n** [Uberspace/lab#1455]
Since the last git pull, freshly uploaded images only appear as placeholders. The same applies to the filter suggestions.
Both in the web interface and in the iOS app. I can't find the error, would appreciate help.

Troubleshooting:
Bootstrap: Writable ✅
Storage: Writable ✅
DATABASE Ping: Pong! Connected to DB "mpixelfed" ✅
REDIS Ping: Pong! Connected to Redis ✅
ACTIVITYPUB instance actor created: ✅ true
ACTIVITYPUB instance actor cached: ✅ true
OAUTH enabled: ✅ true
OAUTH token_expiration 365 days
OAUTH public key exists: ✅ true
OAUTH private key exists: ✅ true

 Important Information
Version: 0.11.4-8bd1b538
Database: mysql (10.3.22-MariaDB)
 PHP Variables
PHP: 8.1.13
PHP INI memory_limit: 256M
PHP INI post_max_size: 2048M
PHP INI upload_max_filesize: 2048M
PHP INI max_file_uploads: 20
PHP INI max_execution_time: 90
PHP INI max_input_time: 60
PHP INI file_uploads (On): 1
PHP INI - Security allow_url_fopen (true): 1
PHP INI - Security allow_url_include (false):
PHP INI - Security expose_php (false): 1
PHP INI - Security display_errors (false): Off
PHP INI - Security display_startup_errors (false):
PHP INI - Security log_errors (true): 1
PHP INI - Security ignore_repeated_errors (false):

**Comment by 23n** [comment]
Hint from the developer:
_Likely a permission issue, make sure you run horizon as the same user as your webserver and that the `bootstrap/` and `storage/` dirs are owned by the same user._
I have no idea how to check this :-)

**Comment by escuco** [comment]
You'll have to insert some new lines for the file system permissions in `/config/filesystems.php` like described in this pull request:
[https://github.com/pixelfed/pixelfed/pull/3825](https://github.com/pixelfed/pixelfed/pull/3825)

After that you have to reread your config with `php artisan config:cache`.

Don't delete `/home/pixelfed/pixelfed/storage/app/m` like described in the pull request, but set the permissions for the older directories manually:

Go to `pixelfed/storage/app/public/` and set the directory permissions recursive with this command: `find ./* -type d -exec chmod 755 {} \;`

That should fix your problem.

**Comment by 23n** [comment]
Thanks, that fixed it. Or almost, I had to set the public folders to chmod 775.

**Comment by 23n** [comment]
Correction. Posting with the iOS app works perfectly. But with the web interface, the error is still there. I have tested different browsers, everywhere the same.

**Comment by 23n** [comment]
Ok, it is fixed now, thank you very much @escuco 
Note to myself: read carefully, read everything, follow the steps described. And copy all the lines, not just the first ones that catch your eye. Sorry for the confusion.
`           'permissions' => [
                'file' => [
                   'public' => 0644,
                   'private' => 0644,
                ],
                'dir' => [
                    'public' => 0755,
                    'private' => 0755,
                ],
            ],`
https://github.com/pixelfed/pixelfed/pull/3825/files/6a8b4f7c2fe32f677c5273ff9e6b80cf5df831e7

**Comment by miri64** [comment]
I have the same problem. Even after setting `config/filesystems.php`:

```console
$ git show --oneline
3cb50af8 (HEAD, tag: v0.11.9) Merge pull request #4601 from pixelfed/staging
```


```diff
diff --git a/config/filesystems.php b/config/filesystems.php
index 6817d5e3..8c6b930c 100644
--- a/config/filesystems.php
+++ b/config/filesystems.php
@@ -49,11 +49,11 @@ return [
             'permissions' => [
                 'file' => [
                     'public' => 0644,
-                    'private' => 0600,
+                    'private' => 0644,
                 ],
                 'dir' => [
                     'public' => 0755,
-                    'private' => 0700,
+                    'private' => 0755,
                 ],
             ],
         ],
```

but even after `php artisan config:cache` (or the [procedure for updates](https://lab.uberspace.de/guide_pixelfed/#updates)), the execute permissions are not set correctly for the directory

```console
$ ls storage/app/public/m/_v2/XXXXXXXXXXXXXXXXXXX/XXXXXXXXXX-XXXXXX/djpUY4xHWPeG/ -ld
drwxr-sr--+ 2 miri64 miri64 4096 29. Okt 16:37 storage/app/public/m/_v2/XXXXXXXXXXXXXXXXXXX/XXXXXXXXXX-XXXXXX/djpUY4xHWPeG/
```

Only after setting the permissions to `drwxr-sr-x+` with `find storage/app/public/ -type d -exec chmod 755 {} \;` the picture is shown correctly. But doing this for every post is obviously out of the question.

**Comment by miri64** [comment]
I also tried the `setgit` and `umask` proposals (the latter in `~/.profile`) proposed here: https://github.com/pixelfed/docs/issues/31#issuecomment-540594319
