### ISSUE TITLE
[MongoDB] Mongo shell no longer ships with server binaries

### ISSUE THREAD

**Issue by daniel-hamm** [Uberspace/lab#1474]
The current version 6.0 of MongoDB does not ship with the server binaries, so the user has to manually download the shell.

From the guide to setup MongoDB:
`mongo admin ~/mongodb/setup.js`

Outputs following error:
`mongo is not avaiable in MongoDB 6.0.`

The guides current version is 4.4.
When I downgrade my shell to 4.4, following the guide, the setup works with following warning:
`WARNING: shell and server versions do not match`

But the setup successfully works to add the user.

The MongoDB Shell can manually be downloaded for Version 6.0:
[https://www.mongodb.com/try/download/shell](https://www.mongodb.com/try/download/shell)

**Comment by daniel-hamm** [comment]
As is see **mongosh** is already available and usable at Uberspace.
So the setup should be updated to use **mongosh** instead of **mongo** for the setup.

**Comment by luto** [comment]
https://github.com/Uberspace/lab/pull/1484
