### ISSUE TITLE
[django] Serving of static files

### ISSUE THREAD

**Issue by mantuko** [Uberspace/lab#1485]
I just followed this guide and I ran into problems with serving of static files.

At the end of the guide there's a part about `uwsgi` which is configured to serve static files. After looking at the history of this guide I think this is part of an old version where `uwsgi` was used which was replaced with `gunicorn`. Also there are some parts missing to really uses `uwsgi`, most important its installation.

So the main question is how to serve static files on uberspace while `gunicorn` serves Django. I'm curious if one could use Apache for this. I want to run my Django-App on a Subdomain and I'm not sure if it's possible to configure the `web backend` to do what I want.

I can serve static files from `/` with `uberspace web backend set / --apache` but how to configure to the `web backend` to serve a specific directory `~/MyDjangoapp/static` via `<subdomain>.<domain>.<tld>/static` is beyond me. I probably could install my own nginx but it seems like a waste with an Apache already running.

Any suggestions?

**Comment by brutus** [comment]
Yes, the Django guide is not really up to date. I'm in the progress of fixing it and hope to have it ready by the end of this week. You can track my progress here: https://github.com/Uberspace/lab/issues/1486

**Comment by brutus** [comment]
For a quick workaround, you can have a look at http://whitenoise.evans.io/

**Comment by mantuko** [comment]
Thank you. Static files are now working. Got a little problem with my csrf token but I guess I look at that tomorrow.

I'll take a look at your changes too. Perhaps I got some input after my fresh install.
