### ISSUE TITLE
[Vaultwarden] fetching the binary doesn't work anymore

### ISSUE THREAD

**Issue by escuco** [Uberspace/lab#1508]
Hello!

The image `vaultwarden/server:alpine`  which is used in the setup and also in the upgrade process isn't available anymore.

So the command

`./docker-image-extract vaultwarden/server:alpine`

throws out an error message "`No layers returned. Verify that the image and tag are valid.`"

Would it be safe to use `./docker-image-extract vaultwarden/server:latest` (instead `:alpine`)?

**Comment by schoeke** [comment]
I agree. In this current form, this recipe is broken. `./docker-image-extract vaultwarden/server:latest` returns the same error now. Not only for the installation itself, but it also concerns updates.

Pinging the original authors in case they can contribute a solution.
@pxlfrk @knhash

**Comment by schoeke** [comment]
Alright, I was wrong. The solution for my case was that I needed to redownload the `docker-image-extractor`. Sorry for the noise.

**Comment by noave** [comment]
so, the guide is working?

**Comment by escuco** [comment]
@noave @schoeke : No. When updating an existent installation pulling and extracting the latest image with the command described in the lab doesn't work.
```
[escuco@cordelia vaultwarden]$ ./docker-image-extract vaultwarden/server:alpine
Getting API token...
Getting image manifest for vaultwarden/server:alpine...
No layers returned. Verify that the image and tag are valid.
[escuco@cordelia vaultwarden]$ 
```

I think we have to use `./docker-image-extract vaultwarden/server:latest` but I'm not sure.

**Comment by pxlfrk** [comment]
Thanks for mentioning me, but sadly I don't have any ressourcen currently to provide a fix. :/

**Comment by escuco** [comment]
I did some investigations - it is like @schoeke described. If the Docker Image Extractor is to old, the mentioned Docker image can't be downloaded.
I've updated the guide with a hint regarding this issue: https://github.com/Uberspace/lab/pull/1527
