### ISSUE TITLE
Guide for HackMD

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/lab#157]
Adapt https://w.h8.lv/s/how_to_install_hackmd_on_uberspace

**Comment by Stunkymonkey** [comment]
i managed to install it.
in the next days i hope to make an PR.

**Comment by retostauffer** [comment]
Just wanted to do the very same thing (well, [codimd](https://github.com/hackmdio/codimd) these days. I'm on an uberspace6 server. Thus it is important to use a newer version of nodejs and gcc to be able to run the setup. My attempt:

Use different ``gcc` and `nodejs` (codimd required `nodejs 6.x`, tested up to `nodejs 7.5.0`):
```
export PATH=/package/host/localhost/nodejs-7.5.0/bin:$PATH
export PATH=/package/host/localhost/gcc-5.2:$PATH
```
Then, the `bin/setup` script runs smoothly, however, `npm run build` still reports an error (and my process was killed by the host as it used too much memory). So far I was not able to go further :).

**Comment by nichtmax** [comment]
> I'm on an uberspace6 server. 
The lab is Uberspace 7 exclusive for these very reasons ☺️

**Comment by retostauffer** [comment]
My bad, sorry.

**Comment by Stunkymonkey** [comment]
i did it on uberspace 7 with codimd

**Comment by Stunkymonkey** [comment]
can be close due to my merged PR #224

**Comment by Stunkymonkey** [comment]
@nichtmax this can be closed due to:
- hackmd was renamed to codimd
- and has been merged in #224

**Comment by Stunkymonkey** [comment]
[here you can read it has been renamed](https://github.com/hackmdio/codimd#hackmd-ce-became-codimd)

**Comment by nichtmax** [comment]
👍
