### ISSUE TITLE
[hedgedoc] check for new nodejs version compatibility

### ISSUE THREAD

**Issue by noave** [Uberspace/lab#1601]
Nodejs 12 / 14 / 16 are EOL and wont be available on Uberspace any longer.

Check if this guide works with Nodejs18 or Nodejs20 and update it accordingly. Otherwise, if you cannot fix it with the new versions mark the guide as broken like it is described here: https://github.com/Uberspace/lab/blob/main/BROKEN_GUIDES.md 

_(This issue has been created automatically, the guide might already be up to date, in this case you can just comment and close the issue here)_

**Comment by DjCrays** [comment]
As stated in the official docs from hedgedoc, it states that you can use from Node.js Version 16 up to the latest Versions. It recommends the latest LTS Versions, but should work with any Version >16 

see: https://docs.hedgedoc.org/setup/manual-setup/

**Comment by EV21** [comment]
FYI: It's already done
see https://github.com/Uberspace/lab/pull/1554
