### ISSUE TITLE
[Synapse] Explain how to add sliding sync proxy

### ISSUE THREAD

**Issue by tillmannheigel** [Uberspace/lab#1625]
In order to use Element X, one must use the [sliding-sync proxy](https://github.com/matrix-org/sliding-sync). An addition for Synapse should explain that properly.

**Comment by taddydevil** [comment]
Got it working on my instance. But I'm unsure if I setup it correctly and securely. The documentation is really unclear with the proxy and port setup imho.
But my Element X works so far yay

**Comment by nichtmax** [comment]
Here might be some help (untested by us) for setting up sliding-sync proxy which seems to need shell variables in supervisord config: https://uberspace.social/@sebastian@social.burschel.com/111531710670020451

**Comment by tillmannheigel** [comment]
Got it working too, should we compare our config, @taddydevil ?

**Comment by tillmannheigel** [comment]
if I remember correctly, I had to create (or update)

/var/www/virtual/$USER/matrix.$DOMAIN.$TLD/.well-known/matrix/client

```
{
    "m.homeserver": {
        "base_url": "https://matrix.$DOMAIN.$TLD"
    },
    "org.matrix.msc3575.proxy": {
        "url": "https://slidingsync.matrix.$DOMAIN.$TLD"
    }
}
```

**Comment by taddydevil** [comment]
Kk, our config is identical - perfect. And yes, the .well-known entry is urgently needed.

**Comment by tillmannheigel** [comment]
And finally I have found this in my history:

uberspace web backend add slidingsync.matrix.$DOMAIN.$TLD/client/ --http --port 8008

I don't get completely why there is a client/ path appended. Maybe that was just for debugging the shipped js client from the repo.

**Comment by tillmannheigel** [comment]
I just checked the documentation. Wasn't there something additionally required for the client/ path?:

```
location ~ ^/(client/|_matrix/client/unstable/org.matrix.msc3575/sync) {
    proxy_pass http://localhost:8009;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
}

location ~ ^(\/_matrix|\/_synapse\/client) {
    proxy_pass http://localhost:8008;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
}

location /.well-known/matrix/client {
    add_header Access-Control-Allow-Origin *;
}
```

**Comment by taddydevil** [comment]
> I just checked the documentation. Wasn't there something additionally required for the client/ path?:

No, one path is already configured with synapse and the other one that you already mention comes with sliding-sync. It should be totally fine that the whole domain will be directed to the proxy.
