### ISSUE TITLE
[moodle] Check for new PHP version compatibility

### ISSUE THREAD

**Issue by noave** [Uberspace/lab#1659]
PHP 8.0 is EOL and wont soon be available on Uberspace any longer.

Check if this guide works with PHP 8.2 (or at least 8.1) and update it accordingly. Otherwise, if you cannot fix it with the new versions mark the guide as broken like it is described here: https://github.com/Uberspace/lab/blob/main/BROKEN_GUIDES.md

_(This issue has been created automatically, the guide might already be up to date, in this case you can just comment and close the issue here)_

**Comment by mickeyhub** [comment]
I just tried to take all the [Moodle Lab steps](https://lab.uberspace.de/guide_moodle/).
In those steps, there isn't a "use PHP 8.0", step.
Trying this myself `uberspace tools version use php 8.0` did not work, as I received the reply `PHP version 8.0 does not exist.`

Not changing the PHP version, gives several errors in the first **initialize** step, opening the domain:
- Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /var/www/virtual/mick/html/lib/phpminimumversionlib.php on line 56
- Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /var/www/virtual/mick/html/lib/phpminimumversionlib.php on line 56
- Deprecated: Return type of moodle_recordset::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/virtual/mick/html/lib/dml/moodle_recordset.php on line 61
- Fatal error: Method lang_string::__set_state() must take exactly 1 argument in /var/www/virtual/mick/html/lib/moodlelib.php on line 10380

I tried running it, after setting my PHP version to 8.1, but I still received the following errors:
- Deprecated: Return type of moodle_recordset::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/virtual/mick/html/lib/dml/moodle_recordset.php on line 61
- Fatal error: Method lang_string::__set_state() must take exactly 1 argument in /var/www/virtual/mick/html/lib/moodlelib.php on line 10380

**Comment by mickeyhub** [comment]
Created a new issue, following the steps described in the original post: https://github.com/Uberspace/lab/issues/1779
