### ISSUE TITLE
[nextcloud] Check for new PHP version compatibility

### ISSUE THREAD

**Issue by noave** [Uberspace/lab#1660]
PHP 8.0 is EOL and wont soon be available on Uberspace any longer.

Check if this guide works with PHP 8.2 (or at least 8.1) and update it accordingly. Otherwise, if you cannot fix it with the new versions mark the guide as broken like it is described here: https://github.com/Uberspace/lab/blob/main/BROKEN_GUIDES.md

_(This issue has been created automatically, the guide might already be up to date, in this case you can just comment and close the issue here)_

**Comment by schneidr** [comment]
Nextcloud works perfectly with PHP 8.2, I'll update the guide as soon as I get a chance.

**Comment by schneidr** [comment]
I just noticed that the guide is already up to date for PHP 8.2 as of f81dd037bd3f2f0170d34ee9376ed5a0633e50a6. IMO the issue can be closed.
