### ISSUE TITLE
[roundcube] Check for new PHP version compatibility

### ISSUE THREAD

**Issue by noave** [Uberspace/lab#1663]
PHP 8.0 is EOL and wont soon be available on Uberspace any longer.

Check if this guide works with PHP 8.2 (or at least 8.1) and update it accordingly. Otherwise, if you cannot fix it with the new versions mark the guide as broken like it is described here: https://github.com/Uberspace/lab/blob/main/BROKEN_GUIDES.md

_(This issue has been created automatically, the guide might already be up to date, in this case you can just comment and close the issue here)_

**Comment by schneidr** [comment]
Roundcube works perfectly with PHP 8.2. I use it daily. I'll update the guide as soon as I get a chance.
