### ISSUE TITLE
WordPress: install and manage/update with wp-cli

### ISSUE THREAD

**Issue by holehan** [Uberspace/lab#17]
What do you think about a more modern approach to managing WordPress with the official WordPress command line interface [wp-cli](http://wp-cli.org/)? It offers [commands](https://developer.wordpress.org/cli/commands/) to not only install and update the WordPress core but also plugins and themes.

Here's a simple [example from the wp-cli docs](https://developer.wordpress.org/cli/commands/core/) to download and install WordPress:

```sh
# Download WordPress core
$ wp core download --locale=nl_NL
Downloading WordPress 4.5.2 (nl_NL)...
md5 hash verified: c5366d05b521831dd0b29dfc386e56a5
Success: WordPress downloaded.

# Install WordPress
$ wp core install --url=example.com --title=Example --admin_user=supervisor --admin_password=strongpassword --admin_email=info@example.com
Success: WordPress installed successfully.
```

**Comment by wernermo** [comment]
@holehan I'm always open for more modern approaches, thanks for the feedback! This seems to be a chicken-and-egg-problem though. How do you get the `wp` tool without installing WordPress? The [official guide](https://codex.wordpress.org/Installing_WordPress#Automated_Installation) is very close to our guide.

**Comment by jonmz** [comment]
Doesn't seem like a chicken-and-egg problem here, as wp-cli [can be installed standalone](https://wp-cli.org/de/#installation) as a PHAR file. We could even think about providing it as a feature, probably..?

**Comment by wernermo** [comment]
We will provide `wp-cli` globally.

**Comment by SalocinHB** [comment]
Postponed until wp-cli is pre-installed

**Comment by nichtmax** [comment]
There you go: https://manual.uberspace.de/en/changelog.html#v7-1-2
