### ISSUE TITLE
Announce New Guides

### ISSUE THREAD

**Issue by knhash** [Uberspace/lab#1707]
I come by the respository once in a couple weeks to see if there are any new guides, in the issues or pull requests, that I can try out on my server. There is a whole self hosted community which would also be interested in these. I wanted to build myself a monitoring tool and link it with ntfy (hosted on uberspace itself, ha!) to ping me when a new guide is released but then I thought of something better.

Is it ok if I submit Uberspace Lab repo to https://www.trackawesomelist.com/#contribution ? It publicly tracks updates and can also serve as an announcement board for new, interested, hosting enthusiasts 😄

**Comment by nichtmax** [comment]
That's a great idea! You're very welcome to add us to the list @knhash?

**Comment by knhash** [comment]
Unfortunately it looks like the way they track updates are via changes to a specific markdown file. So this will not be possible in here. Welp.

Closing this issue.
