### ISSUE TITLE
gitea 1.5.0 crashes

### ISSUE THREAD

**Issue by luto** [Uberspace/lab#171]
https://twitter.com/faheus/status/1030402966581403648

**Comment by ehlers** [comment]
See <https://github.com/go-gitea/gitea/issues/4663>, the base issue is <https://github.com/go-gitea/gitea/issues/2979>.

MariaDB <= v10.2.1 and MySQL <= v5.6 use COMPACT as the default row format, later versions are using DYNAMIC. THE COMPACT row format supports columns up to 767 bytes. The table `topic` uses a varchar(255), which exceeds the max key length as 4*255 = 1020. As Uberspace 7 uses MariaDB v10.1.34, gitea installations / upgrades to 1.5.0 are affected.

To fix that, change table `topic` to DYNAMIC: `ALTER TABLE topic ROW_FORMAT=DYNAMIC;`

You may even want to change all tables to DYNAMIC, this shell command displays the necessary SQL commands (replace \<username\> with your username):
```mysql -B -N -e "SELECT CONCAT('ALTER TABLE \`', TABLE_NAME, '\` ROW_FORMAT=DYNAMIC;') AS mysql FROM INFORMATION_SCHEMA.TABLES WHERE ROW_FORMAT = 'Compact' AND TABLE_TYPE='BASE TABLE' AND TABLE_SCHEMA = '<username>_gitea';"```

I've done that on my gitea v1.5.0 installation on uberspace 7 and it's working great, see my gitea installation at <https://git.bernhard-ehlers.de>.

**Comment by marlemion** [comment]
Same here, on most recent Arch. All the suggestions above did not help!

> 2018/08/22 17:32:39 [I] Log Mode: File(Trace)
> 2018/08/22 17:32:39 [I] XORM Log Mode: File(Trace)
> 2018/08/22 17:32:39 [I] Cache Service Enabled
> 2018/08/22 17:32:39 [I] Session Service Enabled
> 2018/08/22 17:32:39 [I] Migration: Reformat and remove incorrect topics
> 2018/08/22 17:32:39 [I] This migration could take up to minutes, please be patient.
> 2018/08/22 17:32:39 [...itea/routers/init.go:60 GlobalInit()] [E] Failed to initialize ORM engine: migrate: do migrate: Sync2: Error 1709: Index column size too large. The maximum column size is 767 bytes.
> 

Any other idea?

**Comment by ehlers** [comment]
I haven't tested, but with Uberspace 7.1.15 and it's MariaDB 10.3 this issue should be resolved. The default row format is now DYNAMIC.

```
$ mysql -e "show variables like 'innodb_default_row_format'"
+---------------------------+---------+
| Variable_name             | Value   |
+---------------------------+---------+
| innodb_default_row_format | dynamic |
+---------------------------+---------+
```

**Comment by luto** [comment]
Yes, works just fine. Thanks! :)
