### ISSUE TITLE
Footer layout

### ISSUE THREAD

**Issue by 927589452** [Uberspace/lab#18]
On certain devices the footer version date overlaps with the asteroid, because the sphind line has no line break

**Comment by SalocinHB** [comment]
That is also the case in the desktop version. I don't think it harms readability, do you?

**Comment by 927589452** [comment]
Readability no, so no high priority
And I dont think it is possible because of the scaling asteroid
Only "better" solution I can think of is to make it one line
Build with ... On 

Probably a #wontfix
