### ISSUE TITLE
[actual] guide broken

### ISSUE THREAD

**Issue by SalocinHB** [Uberspace/lab#1802]
actual is broken with versions v24.7.0 and higher due to incompatible dependency on bcrypt v5.1.1

**Comment by wysiib** [comment]
i am currently using v24.9.0 on uberspace, but downgrading actual to crypt v5.1.0 which still seems to be compatible with uberspace v7. Could update the guide, but not sure if this is a "desirable setup"? Should the lab include description on how to change dependencies, etc. to get something installed?
