### ISSUE TITLE
[Writefreely] Guide is broken because glibc 2.28 is needed

### ISSUE THREAD

**Issue by escuco** [Uberspace/lab#1816]
The Writefreely upgrade from v0.15.0 to v0.15.1 ([https://github.com/writefreely/writefreely/releases/tag/v0.15.1](https://github.com/writefreely/writefreely/releases/tag/v0.15.1)) is no longer possible, because glibc 2.28 is needed, which is not available on U7.

I tried the suggested workaround (compiling Writefreely from scratch with `make build`, but this doesn't work because of timeout errors.
[https://github.com/writefreely/writefreely/issues/1064](https://github.com/writefreely/writefreely/issues/1064)

So Writefreely users are currently stuck on Writefreely v0.15.0.

Maybe anybody has an idea to fix this?
This is also an information for @thisven , who is the author from this guide.

**Comment by thisven** [comment]
Thanks for bringing this up. Yeah, it seems like we are stuck at the moment. Maybe we can check again, if the admins upgrade glibc.

**Comment by DrPity** [comment]
Same here. Any update when this will be fixed on Uberspace?

**Comment by nichtmax** [comment]
Unfortunately there is no easy way for us to update glibc, Uberspace 7 is CentOS 7 under the hood and glibc 2.17 is the latest version available for CentOS 7.

We are working full speed ahead on Uberspace 8, and we will be switching to Arch to help mitigate problems like this in the future.

**Comment by nichtmax** [comment]
https://github.com/Uberspace/lab/pull/1832

**Comment by thisven** [comment]
I'm sorry to necro-bump this issue, but I successfully updated writefreely to [version 0.16.0](https://github.com/writefreely/writefreely/releases/tag/v0.16.0), as @thebaer reported our issue here and @sahilmulla provided a fix. 😃
