### ISSUE TITLE
Add guide for The Lounge

### ISSUE THREAD

**Issue by Roang-zero1** [Uberspace/lab#206]
The lounge is a community driven always on web client for IRC.

The website can be found at https://thelounge.chat/.

I am currently working on this guide.

**Comment by noobcoder1983** [comment]
Hi @Roang-zero1 ,

could you please add details how to host it with document root / subdomain too.

Your tutorial works I opened port 9000 but now all domains/subdomains refering to the lounge.

I only want that chat.domain.tld loads the lounge chat.

Thanks in advance.

Regards

**Comment by luto** [comment]
@noobcoder1983 have a look at the general docs about web backends, as this is not specific to the lounge: https://manual.uberspace.de/web-backends.html#specific-path

**Comment by noobcoder1983** [comment]
Thanks great that worked!
