### ISSUE TITLE
Add guide for BookStack

### ISSUE THREAD

**Issue by XOFDE** [Uberspace/lab#209]
https://www.bookstackapp.com/ 
According to their documentation they don't support shared PHP hosting because of too many differences between providers. But maybe it's running on uberspace?

**Comment by nichtmax** [comment]
The [manual installation](https://www.bookstackapp.com/docs/admin/installation/#manual) should work just like that. `composer` is preinstalled. I'll check for the modules.

**Comment by lpsutter** [comment]
Works pretty fine. No problem installiert it on uberspace.

**Comment by danielkratz** [comment]
@XOFDE @lpsutter Does one of you want to write this guide? Otherwise I would do it.

**Comment by XOFDE** [comment]
I don't have any experience with it. Feel free :)
