### ISSUE TITLE
Choose license

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/lab#21]
CC-BY-NC-SA? CC-BY? MIT/BSD?

**Comment by SalocinHB** [comment]
CC-BY-SA or CC-BY-NC-SA

**Comment by nichtmax** [comment]
I don't see any reason for NC. CC-BY-SA sounds good to me.

**Comment by nichtmax** [comment]
CC-BY-NC-SA it is! We already had the problem with other companies stealing our texts.

**Comment by jdoubleu** [comment]
Which version? 2.0 or 3.0?

https://creativecommons.org/licenses/by-nc-sa/2.0/
https://creativecommons.org/licenses/by-nc-sa/3.0/

**Comment by SalocinHB** [comment]
We use 4.0 for the U6 wiki so I'd suggest that.

 https://creativecommons.org/licenses/by-nc-sa/4.0/
