### ISSUE TITLE
Add guide for Kanboard

### ISSUE THREAD

**Issue by stratmaster** [Uberspace/lab#215]
Kanboard is a free and open source Kanban project management software. Its website can be found here: https://kanboard.org/.

I'm currently working on this guide.

**Comment by stratmaster** [comment]
Thank you for merging this pull request #217! Therefore I'm closing this issue...

**Comment by SalocinHB** [comment]
> Thank you for merging this pull request #217! Therefore I'm closing this issue...

Thank you. If you use `Closes #215` (replacing the number, of course) in your PR in future, this will happen automatically upon merge.

https://help.github.com/articles/closing-issues-using-keywords/
