### ISSUE TITLE
Add guide for a private composer satis repository

### ISSUE THREAD

**Issue by pascaliske** [Uberspace/lab#227]
Little tool for generating a static site with private composer packages.
See official [docs](https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md) for more information.

**Comment by ihmels** [comment]
Isn't this issue [solved][1]?

[1]: https://lab.uberspace.de/guide_satis.html

**Comment by pascaliske** [comment]
Yes, forgot to close it. Thanks! 🙂
