### ISSUE TITLE
add contributing guidelines

### ISSUE THREAD

**Issue by luto** [Uberspace/lab#23]
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

A contribution guideline should outline ...

* which kinds of issues and pull requests we'd like to see
* which format those issues should have
* which format, language and style new guides should have
* formalities (e.g. licensing)
* a (short) CoC
* tell people to use feature branches, how to do it and how to fix a butchered master
* ask them to leave a name and optionally a link to their homepage/blog for hall of fame
* probably more :package:

**Comment by jpbernius** [comment]
Should the guide in [`source/README.md`](https://github.com/Uberspace/lab/blob/master/source/README.md) go in the `CONTRIBUTING.md` as well?

**Comment by luto** [comment]
the guide in `source` is more of a style guide. It will get its own document.

**Comment by noave** [comment]
even when the contributing guideline might be improved, this issue is imho fixed
