### ISSUE TITLE
Rework all guides for network namespaces

### ISSUE THREAD

**Issue by luto** [Uberspace/lab#244]
Users will soon get their own network namespace.

- [ ] Like documented in the internal u7/manual issues, the currently used `RewriteRule ... [P]` proxies will break in the future. Replace all of them with the new `uberspace web web backend set` command.
- [ ] services need to listen on `0.0.0.0`
- [ ] simplify port generation, since users no longer share a port space. They can just use standard ports >1024.
- [ ] remove any X-Use-Forwarded-Host hacks

**Comment by karfau** [comment]
Just a question because this is the first time I read about this topic: does that mean some sites will break if they don't apply some changes? When will that happen? Where can related information be found?

**Comment by luto** [comment]
> Where can related information be found?

In a blog post announcing the whole thing in the near future :) We aim to break nothing!
