### ISSUE TITLE
reset an U7 account for guides

### ISSUE THREAD

**Issue by ezzra** [Uberspace/lab#258]
Is there a way to reset an U7 account to make sure that you are in a clean environment for testing a guide? In the past I deleted my account and created a new one using uberspace.de, but that's a slightly tiring thing to do (wait for creating, set up password, ssh, email...)

would like to have a command `$ uberspace destroy-everything-and-start-new-yes-i-know-what-iam-doing`

**Comment by dkipp** [comment]
yes, that funktion is needed - at least I'm now looking for it ;-)
Does it exist already?

**Comment by kmichl** [comment]
Looking forward to an update, too.

**Comment by jgefele** [comment]
👍

**Comment by ezzra** [comment]
I today created a simple dirty script to create accounts, initially only for myself, but maybe its useful for this problem too. I will add a delete/reset option so you can keep the uberspace clean. 

https://gist.github.com/ezzra/664d4ec51355f0f3d939b5172deb0371

(I hope thats not making bad vibes @uberspace? because of auto-creating accounts ... code is no big magic)

**Comment by ezzra** [comment]
ok I had a very rainy weekend and it ended up in this tool, its also capable to reset (recreate) an account:

https://github.com/ezzra/uberspace-dash-cmd

**Comment by luto** [comment]
Lab issues are for lab features/guides, not U7 features.
