### ISSUE TITLE
Open Project guide no longer works

### ISSUE THREAD

**Issue by komaspieler** [Uberspace/lab#293]
[source/guide_openproject.rst](https://github.com/Uberspace/lab/blob/master/source/guide_openproject.rst) appears to no longer work with

**a) the current version of the release branch**

Setup terminates during build (`./bin/rake assets:precompile`) with the error

```
92% chunk asset optimization TerserPlugininternal/child_process.js:313                    
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:313:11
```
The error appears to also be memory related (see b) since it is sometimes exchanged for **ENOMEM** as well.

**b) with the tested version 8.1.0 (using [openproject-ce/tags/v8.1.0](https://github.com/opf/openproject-ce/tree/v8.1.0))**

Setup terminates during build (`./bin/rake assets:precompile`) with the error

```
92% chunk asset optimization UglifyJSPluginfs.js:675                                     
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: ENOMEM: not enough memory, read
```

**Steps to reproduce either issue:**

- follow the steps of the tutorial until `./bin/rake assets:precompile`

On closer inspection, it appears unlikely that OpenProject is going to work on U7 since their [system requirements](https://github.com/opf/openproject-ce/blob/stable/8/docs/installation/system-requirements.md) by now ask for at least 4 GB of RAM, making it incompatible with the available 1.5 GB for one user.

I observed memory usage during the build process (on _boethin_) and ~1.5 GB were indeed exceeded upon which the processes were killed. :-(

**Comment by nichtmax** [comment]
removed in commit 3bcc068
