### ISSUE TITLE
Guide for Mattermost 

### ISSUE THREAD

**Issue by hanzei** [Uberspace/lab#298]
With the recently added feature to add custom http backends its finally possible to run Mattermost on U7.

I would like to provide a guide for this.

**Comment by ezzra** [comment]
did you succesfully install mattermost on uberspace? I guess that it needs to much RAM..

**Comment by hanzei** [comment]
Yes, I did install a Mattermost server and it runs fine with a few users.

**Comment by schoeke** [comment]
Hey, I plan to try and install mattermost on U7 soon as well. If you want to publish it still, might be good to do it soon. Otherweise I might publish before you :o

**Comment by hanzei** [comment]
@schoeke Please go ahead

**Comment by master2go** [comment]
Hello 
it would be great to have a guide for it. I don’t know how to install on uberspace
