### ISSUE TITLE
Guide for Ejabberd

### ISSUE THREAD

**Issue by Schlumpf** [Uberspace/lab#304]
It would be nice to have a guide how to install [Ejabberd](https://www.ejabberd.im).
There is a old guide here: http://ejabberd.jandieckmann.de.
Another guide for installing a modern Ejabberd instance on Debian can found here: https://www.kuketz-blog.de/ejabberd-installation-und-betrieb-eines-xmpp-servers

**Comment by SalocinHB** [comment]
That’s not possible without opening ports

**Comment by luto** [comment]
Well, there is [BOSH](https://docs.ejabberd.im/admin/configuration/#enabling-bosh-support), which enables jabber over HTTP. As far as I know, it's even widely supported in clients.

**Comment by dahanbn** [comment]
Opening ports is possible now. It was in the 7.3.0 Uberspace update.

**Comment by fm0de** [comment]
Hi,
I am running ejabberd 19.05 on uberspace 7.
I can write a guide in the next weeks which describes the compilation and configuration of ejabberd. 
Stay tuned.

**Comment by fm0de** [comment]
#444

**Comment by luto** [comment]
https://lab.uberspace.de/guide_ejabberd.html
