### ISSUE TITLE
problems with gitea guide

### ISSUE THREAD

**Issue by ezzra** [Uberspace/lab#314]
I experienced problems when using the gitea guide, after setting the configurations in the webfrontend, I got a proxy error page shown:

```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /install.

Reason: Error reading from remote server
```
Afterwards, the /install path was no longer available (404) and I tried to login, but that didnt work. So I checked the mysql user table, which was empty, although I created an admin user. I managed it by using the gitea `admin create-user --name myname --password asecurepassword --email me@example.com` command. 

Maybe someone else knows where this problem comes from. I hope, that the rest of the installation was ok and I wont encounter other problems.

**Comment by luto** [comment]
works just fine for me with v7.1.2 on a fresh uberspace. Which version did you try?

**Comment by ezzra** [comment]
I installed again yesterday for another project and it worked out fine, so might have been a glitch in the connection whatsoever.
