### ISSUE TITLE
Access on own Let’s Encrypt Certificates

### ISSUE THREAD

**Issue by maitrenageur** [Uberspace/lab#334]
Hi,

Uberspace7 supports own Let’s Encrypt certificates automatically. That is perfect.

But during the guide creation to install and configure a Synapse server (the reference implementation of the Matrix protocol) as own chat and group communication homeserver, i found out, that i have no access on the created certificates (files), to consider these in the synapse configuration.

From my point of view, it would be great, to have access on this certificates, not only for my case. Also to support an encrypted communication for other projects too, like ejabberd etc.

FM

**Comment by nichtmax** [comment]
We're looking into it and I'll keep you posted.

**Comment by nichtmax** [comment]
Keep an eye on the change log for 7.3.1 🤞

**Comment by nichtmax** [comment]
[Added in 7.3.1.1](https://manual.uberspace.de/web-https.html#certificate-access)
