### ISSUE TITLE
Update of the Ghost documentation 

### ISSUE THREAD

**Issue by MaluNoPeleke** [Uberspace/lab#337]
I have updated the Ghost documentation to make use of web backends.
Please take a look at https://github.com/Uberspace/lab/pull/336

**Comment by MaluNoPeleke** [comment]
Updated again using the web-backends branch + adding an updating script: https://github.com/MaluNoPeleke/lab/tree/web-backends

**Comment by luto** [comment]
Thank you! I'll have a look after we merged the backends branch into master, which should happen this week.

**Comment by MaluNoPeleke** [comment]
Any update on this?

**Comment by luto** [comment]
Sorry about the delay :/ I've added your changes manually, since both web backends and and `:manual:` were refactored globally in parallel or before your commit. Thanks for the script!
