### ISSUE TITLE
Guide for Fathom

### ISSUE THREAD

**Issue by ebroda** [Uberspace/lab#342]
https://usefathom.com/ provides real-simple, privacy centered tracking of your website usage. "Fathom Analytics provides simple, useful websites stats without tracking or storing personal data of your users."

I'd just deployed it to an Uberspace and going to write a guide for the Uberlab.

**Comment by sdoering** [comment]
Locking forward to this. I would love to try out fathom - did you (@ebroda) stumble upon bigger roadblocks? Or was it more or less straightforward? 

Thanks in advance.

**Comment by youngpilot** [comment]
I can't get fathom to run on my uberspace. Fathom states ERROR: File not executable. 
Can somebody help?
