### ISSUE TITLE
add contributors to each guide

### ISSUE THREAD

**Issue by luto** [Uberspace/lab#35]
We should credit all the nice people who have written guides for our lab. Maybe a nice box listing their names at the top or bottom of each guide will do?

**Comment by nichtmax** [comment]
Can we use the [API](https://developer.github.com/v3/repos/#list-contributors) for this?

**Comment by luto** [comment]
The API returns the needed date on a per-repo basis, not per-file/guide. Git can of course generate the same list, but that looks a little messy right now:

```
                               
927589452 <927589452@users.noreply.github.com>
luto <m@luto.at>
Moritz <988418+nichtmax@users.noreply.github.com>
Moritz Werner <moritz@team.uber.space>
Nico Graf <SalocinHB@users.noreply.github.com>
Nicolas Graf <nico@team.uber.space>
wernermo <mail@mwerner.eu>
```

I don't think we'll get away without a little manual love.

**Comment by nichtmax** [comment]
@luto How about the [sectionauthor directive](http://www.sphinx-doc.org/en/stable/markup/misc.html#directive-sectionauthor)? We could use that in the footer then.

**Comment by luto** [comment]
I like it.
