### ISSUE TITLE
mongodb port in use

### ISSUE THREAD

**Issue by dominikg** [Uberspace/lab#350]
Hi,

recently the mongodb guide was changed to remove custom port selection.
I followed this guide today on host pizarro and got the following error for both 127.0.0.1 and 0.0.0.0 as ip.

> 2019-04-03T09:59:05.833+0200 E STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use

it started up fine when using a custom free port

**Comment by luto** [comment]
sorry about that! We are currently in kind of a limbo with 60% of hosts having web backends already (so a custom port is not needed) and 40% running without them. The remaining hosts will follow shortly.
