### ISSUE TITLE
django doesn't start with sqlite

### ISSUE THREAD

**Issue by luto** [Uberspace/lab#352]
The U7 sqlite is too old for django 2.2. Change the guide to use MySQL instead for now.

**Comment by rikroe** [comment]
Just for documentation, another workaround could be defining a specific Django version, i.e. ``pip install django<2.2``. 

Although probably in the end an update of SQLite is needed as you never can control all dependencies. However if you install the Django dependency manually before your other packages, it might work correctly.

**Comment by nichtmax** [comment]
You could just use MySQL instead of sqlite.

**Comment by nichtmax** [comment]
[Guide](https://github.com/Uberspace/lab/blob/master/source/guide_django.rst)

**Comment by Finn0811** [comment]
Oh, looks like I need to update my guide 🙈

**Comment by copykatze** [comment]
Might this help? https://github.com/Uberspace/lab/pull/398

I am not an expert by far, but it seems to work for me.

**Comment by luto** [comment]
The django guide works just fine using mysql now, yes. Having sqlite would still be nice for simple apps. We're working on a newer sqlite version, but are currently busy with a different project.

**Comment by FriedrichFroebel** [comment]
Compiling SQLite3 from (the amalgamation) source (`gcc -o sqlite shell.c sqlite3.c -lpthread -ldl`) and adding the corresponding path to the path variable (`PATH="$HOME/sqlite/sqlite-amalgamation-3280000:$PATH"`) inside `~/.bashrc` (to check it, I sourced this file afterwards) seems to work as well. (At least I could setup and use the dummy project without problems afterwards.)
