### ISSUE TITLE
CodiMD is not able to build anymore

### ISSUE THREAD

**Issue by luksal** [Uberspace/lab#361]
I'm trying to install the latest CodiMD version 1.3.2, but the installation always breaks when web pack tries to use the terser plugin. In the lab manual it's stated that you should remove the ParallelUglifyPlugin but it's not used anymore.
After executing `node run build` I get the following error message:
```
> CodiMD@1.3.2 build /home/lsv7/codimd
> webpack --config webpack.prod.js --progress --colors --bail

 96% [0] chunk asset optimization TerserPluginGetötet
```

**Comment by luksal** [comment]
Quick workaround: If you copy the `webpack.dev.js`to `webpack.prod.js`, then the build is running fine

**Comment by luto** [comment]
This guide has seen a lot of changes since this issue was opened. If it is still broken, please open a new issue.
