### ISSUE TITLE
mailman3 hyperkitty

### ISSUE THREAD

**Issue by ezzra** [Uberspace/lab#363]
sorry for bringing up more mailman3 stuff ;)

It looks like the guide does not provide a proper way to keep hyperkitty (the archiving module) running. There needs to be setup some more crontabs and a qcluster process:

http://docs.list.org/en/latest/config-web.html#scheduled-tasks-required
http://docs.list.org/en/latest/config-web.html#running-the-task-queue-required

Before this hyperkitty did not show any archived lists for my installation. After I called the commands it does, but still no threads/emails. Mh, maybe someone else is already more experienced with the configuration here. Otherwise I would need to work on this.

**Comment by rikroe** [comment]
Your comments are very appreciated, at least now I know that somebody actually puts it to use and it wasn't for nothing :D

I actually have a local commit adding a note on top stating that archiving is not working. Will create a PR for it soon. As I don't need it for my usecase, I'll probably skip trying to get it to work, sorry :worried: .

**Comment by richard-dg** [comment]
Hi @ezzra, hi @rikroe,

thanks for the guide and thanks for this issue. I also stumbled upon the missing cronjobs for hyperkitty. I'm not sure if I understand correctly, that's why I'm asking. 

I just need to add those 7 jobs to my crontab?
> http://docs.list.org/en/latest/config-web.html#scheduled-tasks-required

What about this? How to set this up on an uberspace? Is this also a cronjob?
> http://docs.list.org/en/latest/config-web.html#running-the-task-queue-required
Thanks for clarification,

Richie

**Comment by rikroe** [comment]
I'd guess you just need to add the 7 jobs to your [crontab](https://manual.uberspace.de/daemons-cron.html). 
The task queue should already be setup in the guide (see steps `~/uwsgi/apps-enabled/mailman-suite.ini`), but not 100% about this.
You have to try :) If only the cronjobs are missing, please make a small PR.

**Comment by noave** [comment]
hyperkitty works now with #772

**Comment by luto** [comment]
https://lab.uberspace.de/guide_mailman-3.html
