### ISSUE TITLE
reference guide in commit message

### ISSUE THREAD

**Issue by ezzra** [Uberspace/lab#370]
I would enjoy having a "commit message policy" to see immediately which guide is affected by a new commit. Just a line in `STYLE.md` that requests authors to mark their commits like `[tool] add update info` or just `tool - add update info`

That might be my special problem because I subscribed to the commit feed, but maybe its also good for others too :)

**Comment by nichtmax** [comment]
Great idea! PR is welcome ☺️

**Comment by luto** [comment]
I vote for the `[tool] add update info` syntax.
