### ISSUE TITLE
Guide for Golang

### ISSUE THREAD

**Issue by ces92** [Uberspace/lab#379]
A guide for installing Go https://golang.org/

**Comment by Snapstromegon** [comment]
If I'm correct this guide should be easy:
Download current version from [website](https://golang.org/dl/)
```
$ wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
```

Extract it to a basedir e.g. ~/go (first extracted level is go, so go would be created)
```
$ tar  -xzf go$VERSION.$OS-$ARCH.tar.gz # (tab complete would help)
```

And add ~/go/bin to path (needs to persist in .bashrc)
```
export PATH=$PATH:/home/$USER/go/bin
```
