### ISSUE TITLE
Ease of Use: Databases

### ISSUE THREAD

**Issue by 927589452** [Uberspace/lab#39]
Should the generation of needed databases be included ?

**Comment by nichtmax** [comment]
If this is a necessary step for setup: yes. If the tools do this be themselves: no.

**Comment by ezzra** [comment]
In the etherpad guide I used this code to easily create MySQL DB within terminal:

    mysql -e "CREATE DATABASE ${USER}_etherpad;"

The var $USER does already care for the usernaming thing.
