### ISSUE TITLE
[Feature Request] add own certificates (to the load balancer)

### ISSUE THREAD

**Issue by 927589452** [Uberspace/lab#390]
I would be nice to be able to add an own certificate to the balancer which would help with #334 as a own let's encrypt certificate could be added to the balance, meaning there is no need for the user to access it ( or maybe push the certificate generation back to the userspace)
Also would allow for users to buy their own .onion certs

**Comment by luto** [comment]
Users can now access the let's encrypt certificates, which eliminates most use cases for this. We're not planning a feature to upload custom certificates at the moment. Certs for .onions are in a rather unfortunate situation: there is only one CA offering them at rather high prices :/ Additionally, many benefits of HTTPS are already provided by HTTP over tor.
