### ISSUE TITLE
supervisord include in all guides

### ISSUE THREAD

**Issue by 927589452** [Uberspace/lab#414]
the most part for supervisord could be move into a snippet, except the supervisord unit

**Comment by luto** [comment]
Can you name an example? The current supervisord sections (e.g. [guide_etherpad.html#setup-daemon](https://lab.uberspace.de/guide_etherpad.html#setup-daemon)) contain tool-specific paths and the tool name in console output. Generalizing the config part makes it less copy-paste-able. Removing the tool name from console output might confuse reads, but sounds reasonable to reduce clutter.

**Comment by 927589452** [comment]
exactly the latter would have been my suggestion
the service name could be replaced with SERVICE leading to a more uniform snippet, as some tools split the parts and put more information into it (e.g. https://lab.uberspace.de/guide_postgresql.html?highlight=postgresql#setup-daemon)
the first part is quite important, as a tool may need to be started on a special way like using the virtualenv's python

**Comment by 927589452** [comment]
also the snippet (or maybe the manual https://manual.uberspace.de/daemons-supervisord.html#supervisord ) should hint at supervisord not sourcing any environment variable like the ones from .bash_rc and .bash_profile

**Comment by luto** [comment]
- [ ] look for all guides using supervisord
- [ ] replace the `supervisorctl reread/update/status` part with `.. include:: includes/supervisord.rst`

**Comment by 927589452** [comment]
grep supervisord source/* |  awk -F ':' '{print $1 }' | uniq

- [ ] source/guide_autossh.rst
- [ ] source/guide_babybuddy.rst
- [ ] source/guide_buildbot.rst
- [ ] source/guide_codimd.rst
- [ ] source/guide_cryptpad.rst
- [ ] source/guide_django.rst
- [ ] source/guide_embetty.rst
- [ ] source/guide_etherpad.rst
- [ ] source/guide_ghost.rst
- [ ] source/guide_gitea.rst
- [ ] source/guide_gitlab-runner.rst
- [ ] source/guide_hugo.rst
- [ ] source/guide_invoiceninja.rst
- [ ] source/guide_jenkins.rst
- [ ] source/guide_jingo.rst
- [ ] source/guide_mailman-3.rst
- [ ] source/guide_mailman.rst
- [ ] source/guide_miniflux.rst
- [ ] source/guide_mongodb.rst
- [ ] source/guide_mumble.rst
- [ ] source/guide_postgresql.rst
- [ ] source/guide_pretix.rst
- [ ] source/guide_prometheus.rst
- [ ] source/guide_puma.rst
- [ ] source/guide_radicale.rst
- [ ] source/guide_redis.rst
- [ ] source/guide_resilio.rst
- [ ] source/guide_synapse.rst
- [ ] source/guide_syncthing.rst
- [ ] source/guide_the-lounge.rst
- [ ] source/guide_up1.rst
- [ ] source/guide_xbrowsersync.rst
- [ ] source/guide_znc.rst
