### ISSUE TITLE
mosh wrong license

### ISSUE THREAD

**Issue by mroethke** [Uberspace/lab#415]
The guide says moshs license is "OCB license", which is not true. Mosh is licensed under the GPLv3.

The file [`ocb-license.html`](https://github.com/mobile-shell/mosh/blob/master/ocb-license.html) in the repo root of mosh contains the license grant for the OCB block cipher mode, not the project license. I guess this is the origin of the mistake.
The project license can be found in the file [`COPYING`](https://github.com/mobile-shell/mosh/blob/master/COPYING).

**Comment by luto** [comment]
whoops. thanks!
