### ISSUE TITLE
Multiple Ports in one Guide

### ISSUE THREAD

**Issue by 927589452** [Uberspace/lab#42]
If I need to use multiple ports  in one guide,
should I just use 9000,9001,9002, are they surely blocked?

**Comment by nichtmax** [comment]
We can make sure that these are blocked ☺️ How about 9000 - 9010?

**Comment by nichtmax** [comment]
Ports 9000 - 9010 are blocked in U7.1.2

**Comment by 927589452** [comment]
this sounds good

I cannot think of a tool ATM which uses more than 10 ports
