### ISSUE TITLE
Guide for mailtrain

### ISSUE THREAD

**Issue by ezzra** [Uberspace/lab#430]
I will add a guide for mailtrain, just having problems with html compiling in sphinx at the moment.. so if anyone else wants to go forward more fast, just say it here :)

**Comment by heinrichreimer** [comment]
Any update on mailtrain?

**Comment by felixfoertsch** [comment]
I just set it up on my U7. Since there has not been any activity on this, I'll document my steps.

**Comment by heinrichreimer** [comment]
Very nice, thank you Felix!

**Comment by felixfoertsch** [comment]
@heinrichreimer It's done, in case you want to test it. 😁

**Comment by felixfoertsch** [comment]
@luto This can be closed, I think? 101b9432f6c95c4f590c0260261e2b6c085ce7ab
