### ISSUE TITLE
Synapse error

### ISSUE THREAD

**Issue by samuelhaeussler** [Uberspace/lab#439]
Getting this error in homeserver.log

psycopg2.OperationalError: could not connect to server

Postgres is running:
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      32179/postgres

**Comment by 927589452** [comment]
you want to connect to the postgres database on the local socket;
is it configured that way?

**Comment by samuelhaeussler** [comment]
Just configured like in the guide ;-)

[program:synapse]
command=python3.6 -m synapse.app.homeserver -c %(ENV_HOME)s/synapse/homeserver.yaml
autostart=yes
autorestart=yes
environment=
       PATH="%(ENV_HOME)s/opt/postgresql/bin/:%(ENV_PATH)s",
       LD_LIBRARY_PATH="$LD_LIBRARY_PATH:%(ENV_HOME)s/opt/postgresql/lib",
       PGPASSFILE=%(ENV_HOME)s/.pgpass,
       PGHOST=localhost,
       PGPORT=5432

**Comment by 927589452** [comment]
I would just point you to the best practices 
one uberspace per service
and use an announced subdomain for synapse like
matrix.my.domain
and put the wellknown file on your main web service

**Comment by samuelhaeussler** [comment]
I tried that, but it didn't work out:

Synapse is running on matrix.example.com

_matrix._tcp.example.com 3600 IN SRV 10 0 443 matrix.example.com.
Also the A-Records for matrix.example.com are set to the IP of the matrix.example.com host.

So I am not able to communicate with "my self" over @username:example.com and I only can login with @username:matrix.example.com

**Comment by 927589452** [comment]
Please try putting the well-known on example.com

Option B:.well-known announcement
---------------------------------

.. note:: This is the newer method, easier to implement but not supported on older servers.

Setup the directory for the next step:

.. code-block:: console

  [isabell@stardust ~]$ mkdir -p ~/html/.well-known/matrix
  [isabell@stardust ~]$

The federation port can also be announced via a file ``~/html/.well-known/matrix/server``

.. code-block:: json
  :emphasize-lines: 2

  {
    "m.server": "my.domain.name:443"
  }

This has to be made available under ``/.well-known/matrix`` via the web backend:

.. code-block:: console

  [isabell@stardust ~]$ uberspace web backend set /.well-known/matrix --apache
  Set backend for /.well-known/matrix to apache.
  [isabell@stardust ~]$




and point to matrix.example.com on 443
and point the ``uberspace web backend`` to 8008

what does https://github.com/matrix-org/synapse/blob/master/docs/federate.md
say?

**Comment by samuelhaeussler** [comment]
I just tried it with the SRV record. But I solved it with a dedicated port and enabled TLS in the config.

**Comment by luto** [comment]
This guide has seen a lot of changes since this issue was opened. If it is still broken, please open a new issue.
