### ISSUE TITLE
Django test doesn't work

### ISSUE THREAD

**Issue by jonmz** [Uberspace/lab#453]
In the [Django guide](https://lab.uberspace.de/guide_django.html) the user is expected to set `ALLOWED_HOSTS` to the hostname he wishes, which is generally fine.

However at a later point a test is carried out with `curl -I localhost:8000` - this fails with the following message in the error log:

> Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.

Django versions < 2 didn't check `ALLOWED_HOSTS` if `Debug = True` was set (which _is_ set in this guide). Current Django versions _do_ check it, even in debug mode. Therefore I propose to have the user set the following:

`ALLOWED_HOSTS = ['localhost','isabell.uber.space']`

**Comment by luto** [comment]
#516
