### ISSUE TITLE
Django - Install mysqlclient first

### ISSUE THREAD

**Issue by webwart** [Uberspace/lab#454]
Concerns: Django installation manual
https://lab.uberspace.de/guide_django.html

In my case I needed to install the python mysql API, which is not mentioned in the guide. Eventually, it would be good to add this information to the prerequesits section of the guide. I used this CLI command to install the mysqlclient driver.

pip3.6 install mysqlclient --user

Rainer

**Comment by luto** [comment]
https://github.com/Uberspace/lab/commit/93253f5670382b670039d798694bc1ebd50f9b0e
