### ISSUE TITLE
Guide for Grocy

### ISSUE THREAD

**Issue by joa77** [Uberspace/lab#464]
It would be nice to have a guide for grocy https://github.com/grocy/grocy

grocy is a web-based self-hosted groceries & household management solution for your home.

**Comment by 164-dame** [comment]
I am working on this, I will update in this issue when completed.

**Comment by Sub6** [comment]
Any updates?

**Comment by nicogramm** [comment]
@fishofivory are you still working on this?
Otherwise I'd like to contribute it myself, I installed it today. But I wanted to ask beforehand.

**Comment by jskvbinmv** [comment]
Also very interested. I keep getting 403 errors, seems like some permission problem or my settings are wrong. Any advise?

**Comment by luto** [comment]
https://lab.uberspace.de/guide_grocy.html

If there are any problems with this guide, please open a new issue.
