### ISSUE TITLE
Guide for Taskwarrior Server

### ISSUE THREAD

**Issue by seeeq** [Uberspace/lab#478]
I set up **taskd**, a server for synchronizing taskwarrior clients. I could share the procedure. Is this of interest?

https://taskwarrior.org/
https://taskwarrior.org/docs/taskserver/why.html

**Comment by temal-** [comment]
Sounds like an interesting tool. I'd be interested.

**Comment by luto** [comment]
https://lab.uberspace.de/guide_taskd.html
