### ISSUE TITLE
Add guide for installation of YOURLS

### ISSUE THREAD

**Issue by markum** [Uberspace/lab#487]
The official installation instructions: https://yourls.org/#Install fail with a "HTTP ERROR 500".

**Comment by danielkratz** [comment]
I did a quick test install which worked right away. Is it possible that you tried to install YOURLS in an additional DocumentRoot (other folder as html named like your domain?). In this case the generated .htaccess of YOURLS might not work out of the box. 

Anyway I will right a little guide for YOURLS.

**Comment by markum** [comment]
thanks!
