### ISSUE TITLE
Nextcloud guide: data directory location

### ISSUE THREAD

**Issue by chrrel** [Uberspace/lab#510]
During the installation process Nextcloud offers to choose a location for the data directory. From a security perspective it is desirable to place it outside of the webserver's DocumentRoot like it was already mentioned in the corresponding [U6 wiki page](https://wiki.uberspace.de/cool:nextcloud#einrichten_von_nextcloud).

This hint is missing in the [U7 guide](https://lab.uberspace.de/guide_nextcloud.html). Hence, I suggest to add a paragraph to the _Installation_ section.

> You can choose where Nextcloud is going to store your data files. It is recommended to place them outside of the webserver's DocumentRoot, e.g. `home/isabell/nextcloud_data/`.

**Comment by luto** [comment]
that's right! would you like to submit a pull request for that?
