### ISSUE TITLE
git clone without history?

### ISSUE THREAD

**Issue by ezzra** [Uberspace/lab#55]
Should `git clone` commands be used wit `--depth 1` to omit history data? Most of the users wont need them, and if so they would know how to get them. 
Sometimes commit histories are quite large and downloading them again and again just creates traffic and harms the environment ;)

**Comment by tocsinDE** [comment]
In case you only need the current state of master branch - no problem at all and a good idea.
But when one wants to use a specific tag or version the history is needed.

**Comment by nichtmax** [comment]
Even [https://services.github.com/on-demand/downloads/github-git-cheat-sheet/](github) uses plain `git pull` in their cheat sheets. The focus of the guides should be simplicity.
