### ISSUE TITLE
Guide for "isso" commenting platform

### ISSUE THREAD

**Issue by ReyNow** [Uberspace/lab#569]
I would like to write the guide for the "isso" commenting platform. 

It is powered by python and can be used to inject commenting functionalities to blogs or other static site generators. It works similar as commento.

**Comment by Fryboyter** [comment]
The installation of Isso does not currently work via pip.

https://github.com/posativ/isso/issues/617

I would therefore wait a little longer until the problem has been solved.

**Comment by ReyNow** [comment]
Yes, you will face the issue but it can be fixed by installing the fitting werkzeug version afterwards. I managed to get it to work some days ago.
