### ISSUE TITLE
composer guide

### ISSUE THREAD

**Issue by ezzra** [Uberspace/lab#57]
[wallabag](https://github.com/Uberspace/lab/issues/54) needs composer, so writing a small composer install guide, too :)

**Comment by nichtmax** [comment]
We will provide composer globally in a few days ☺️

**Comment by ezzra** [comment]
ah great, I have already been surprised why its not available

**Comment by nichtmax** [comment]
There you go: https://manual.uberspace.de/en/changelog.html#v7-1-2
