### ISSUE TITLE
Guide synapse matrix server

### ISSUE THREAD

**Issue by 927589452** [Uberspace/lab#58]
Currently  working on a guide for the synapse matrix server

**Comment by 927589452** [comment]
Waiting for #59

**Comment by glU79z** [comment]
Does this change anything? https://blog.uberspace.de/web-backends-websockets/

**Comment by mulles** [comment]
@927589452  any updates concerning your guide?

**Comment by 927589452** [comment]
i was going to port this to the U7 https://janw.xyz/blog/installing-a-matrix-org-synapse-server-on- uberspace/ (original by @janw )

 I will take at least a week before I can try writing the guide again

**Comment by 927589452** [comment]
> Does this change anything? https://blog.uberspace.de/web-backends-websockets/
I still need a feature thats been announced with U7.3 ( thanks @luto ) [ports], as the matrix server needs to listen for federation servers and I need to set it up with my real dns a  SRV  Record for  _matrix._tcp: to announce the port, unless I can use 8443 or 8008; 
see https://github.com/Uberspace/manual/commit/8cd0cfc3fc2a98766c8d621f689f6a0f6cf20c53 
(or would this be possible in U7.4 with IPv6 at least)

**Comment by luto** [comment]
Web backends should enable you to run synapse behind nginx, as it [can run on 443 behind a load balancer](https://matrix.org/docs/guides/faq#what-ports-do-i-have-to-open-up-to-join-the-global-matrix-federation%3F):

> You can also put Synapse entirely behind an existing TLS load balancer and not expose port 8448 at all. In this situation, Synapse will need to be configured to share the same public TLS certificate as the load balancer (as Synapse uses the public certificate for identity in other areas too, and it has to match the certificate that other servers see when they connect).

The ports feature in a future release will enable you to open ports in the 40.000-61.000 TCP/UDP range. They can be used in a `SRV _matrix._tcp` record, which seems to be the nicer solution. I am not sure how synapse normally handles certificate handling, though. Keep in mind, that you can currently not access the automatically issued let's encrypt certificates.

**Comment by 927589452** [comment]
> The ports feature in a future release will enable you to open ports in the 40.000-61.000 TCP/UDP range. They can be used in a `SRV _matrix._tcp` record, which seems to be the nicer solution. I am not sure how synapse normally handles certificate handling, though. Keep in mind, that you can currently not access the automatically issued let's encrypt certificates.

the last point hinders usage of the load balancer;
for now I will just request a certificate for synapse ( multiple certificates are no problem https://letsencrypt.org/docs/rate-limits/ ) and have to run it "exposed"

**Comment by 927589452** [comment]
so with the new cert access in 7.3.1.1 my current instance is starting
will just check if with the correct tcp_ entry it will federate and afterwoods it should be about a day until the guide is done

**Comment by 927589452** [comment]
federation is not yet working 
sorry

**Comment by DJCrashdummy** [comment]
@927589452 if everything else works well, i would still call such a guide as valuable. :+1: 

for sure federation would be nice to have, but for now better than nothing... and i know some people who disabled federation again, because of the heavy load when users access big rooms.

**Comment by luto** [comment]
Can you share details on what is not working with federation? Thanks!

**Comment by 927589452** [comment]
@DJCrashdummy the current state is this
https://github.com/Uberspace/lab/pull/413

**Comment by 927589452** [comment]
@luto already opened a ticket to dertermine if i made a mistake or v6 and ports do misbehave

**Comment by 927589452** [comment]
the guide is now ready to run 

future additions: 
- federation
- usage of supervisord

**Comment by 927589452** [comment]
supervisord is fixed for me, _but_ I not sure if i should publish it that way;
my supervisord script starts bash, sources .bash_profile and .bash_rc and activates the venv and starts synapse from there;
I will tryout which environments to configure

**Comment by 927589452** [comment]
``[program:synapse]
command=%(ENV_HOME)s/synapse/env/bin/python3.6 -m synapse.app.homeserver -c %(ENV_HOME)s/synapse/homeserver.yaml
autostart=no
autorestart=yes
environment=
        PATH="/home/matrites/synapse/env/bin:%(ENV_HOME)s/opt/postgresql/bin/:$PATH",
        LD_LIBRARY_PATH="$LD_LIBRARY_PATH:%(ENV_HOME)s/opt/postgresql/lib",
        PGPASSFILE=%(ENV_HOME)s/.pgpass,
        PGHOST=localhost,
        PGPORT=5432``

this still feels cumbersome

**Comment by tristan-k** [comment]
Is it possible that the current [Synpase Guide](https://github.com/Uberspace/lab/blob/main/source/guide_synapse.rst) is not up to date? I followed the guide but I'm unable to build matrix-synapse because the Rust compiler can't be found. Even though it is.

```
$ which rustc
/usr/bin/rustc
$ rustc --version
rustc 1.88.0 (6b00bc388 2025-06-23)
```

```
      running build_ext
      running build_rust
      Traceback (most recent call last):
        File "/opt/uberspace/python-venv/lib64/python2.7/site.py", line 703, in <module>
          main()
        File "/opt/uberspace/python-venv/lib64/python2.7/site.py", line 694, in main
          execsitecustomize()
        File "/opt/uberspace/python-venv/lib64/python2.7/site.py", line 548, in execsitecustomize
          import sitecustomize
        File "/tmp/pip-build-env-vzipbwxs/site/sitecustomize.py", line 23, in <module>
          site.addsitedir(path)
        File "/opt/uberspace/python-venv/lib64/python2.7/site.py", line 204, in addsitedir
          addpackage(sitedir, name, known_paths)
        File "/opt/uberspace/python-venv/lib64/python2.7/site.py", line 173, in addpackage
          exec(line)
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-vzipbwxs/overlay/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 34
          f"Register concerns at {report_url}"
          ^
      SyntaxError: invalid syntax
      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      Traceback (most recent call last):
        File "/home/tristank/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
        File "/home/tristank/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
        File "/home/tristank/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 280, in build_wheel
          return _build_backend().build_wheel(
        File "/tmp/pip-build-env-vzipbwxs/overlay/lib/python3.9/site-packages/poetry/core/masonry/api.py", line 58, in build_wheel
          return WheelBuilder.make_in(
        File "/tmp/pip-build-env-vzipbwxs/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 95, in make_in
          wb.build(target_dir=directory)
        File "/tmp/pip-build-env-vzipbwxs/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 132, in build
          self._build(zip_file)
        File "/tmp/pip-build-env-vzipbwxs/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 193, in _build
          self._run_build_command(setup)
        File "/tmp/pip-build-env-vzipbwxs/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 288, in _run_build_command
          subprocess.check_call(
        File "/usr/lib64/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/python3.9', '/tmp/pip-install-57v3n7ae/matrix-synapse_5e81b2dd9a914d70a1691e64c0118436/setup.py', 'build', '-b', '/tmp/pip-install-57v3n7ae/matrix-synapse_5e81b2dd9a914d70a1691e64c0118436/build', '--build-purelib', '/tmp/pip-install-57v3n7ae/matrix-synapse_5e81b2dd9a914d70a1691e64c0118436/build/lib', '--build-platlib', '/tmp/pip-install-57v3n7ae/matrix-synapse_5e81b2dd9a914d70a1691e64c0118436/build/lib.linux-x86_64-cpython-39']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for matrix-synapse
Failed to build matrix-synapse
error: failed-wheel-build-for-install

× Failed to build installable wheels for some pyproject.toml based projects
╰─> matrix-synapse
```

**Comment by tristan-k** [comment]
Got it working. I had to install cargo rust in home with:

```
$ curl https://sh.rustup.rs -sSf | sh

$ source $HOME/.cargo/env

$ which rustc
~/.cargo/bin/rustc
$ rustc --version
rustc 1.88.0 (6b00bc388 2025-06-23)

$ cat ~/.bashrc | grep -C 1 '$HOME/.cargo/env'
# User specific aliases and functions
. "$HOME/.cargo/env"
```
