### ISSUE TITLE
Add guide for turn server (coturn)

### ISSUE THREAD

**Issue by beatstick** [Uberspace/lab#581]
It would be awesome to have a family video-chat with nextcloud talk (or via xmpp jitsi). Unfortunately p2p connections fail as often as not, so a turn server would be the only solution to make this family friendly. 
I think coturn requires libevent which I could not find on the manual page, so I guess it is not supported or has to be installed manually.

**Comment by SalocinHB** [comment]
I've spent a couple of hours on coturn yesterday. It compiles just fine when using `./configure --prefix=$HOME`, and it runs as well. I even managed to start calls with devices on different NATed networks, but after a short while it enters a loop where it tries to attach itself to ports it is already attached to (which fails) and doesn't accept new connections anymore.

**Comment by SalocinHB** [comment]
```
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45120>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45122>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45120>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45122>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45120>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45122>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45120>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45122>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45120>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45122>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45120>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45122>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45120>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45122>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45120>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45122>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45120>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45122>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45120>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45122>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45120>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45122>: errno=98
230: Trying to bind fd 106 to <[fd75:6272:7370:100::2]:45120>: errno=98
230: create_relay_ioa_sockets: no available ports 3
```

**Comment by beatstick** [comment]
Thanks for the input. That sounds pretty good already. Which version of coturn are you using? I think one of the newer versions was buggy, so maybe try a different build. I

**Comment by SalocinHB** [comment]
I think I've figured it out. I forgot to open additional ports for UDP relay endpoints and specify that port range in the config. After I did that, I just managed to start a session with three guests w/o any errors logged. I'll try to write up a guide in the next couple of days.

**Comment by SalocinHB** [comment]
The gist of it is:
- Download and unpack a release ZIP or tarball
- cd to the unpacked directory
- run `./configure --prefix=$HOME`
- `make`
- `make install`
- Place your config file in ~/etc/turnserver.conf and set these options to appropriate values (the ports that you set need to be open): `listening-port`, `tls-listening-port`, `external-ip`, `external-ip`, `min-port`, `max-port`, `fingerprint`, `use-auth-secret`, `static-auth-secret`, `server-name`, `mysql-userdb`, `realm`, `total-quota30`, `cert`, `pkey`, `log-file`, `simple-log`, `pidfile`
- set up a `supervisord` service like this: 
```
[program:turnserver]
command=%(ENV_HOME)s/bin/turnserver -c %(ENV_HOME)s/etc/turnserver.conf
```

**Comment by coderkun** [comment]
Thanks for the brief guide, @SalocinHB. I gave it a quick run and it seems to work fine. Though I have not tested it in action, yet.

For testing the configuration I used [WebRTC samples Trickle ICE](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) (with username/password configuration) and the Nextcloud Talk configuration (with static auth secret).

**Comment by beatstick** [comment]
> I forgot to open additional ports for UDP relay endpoints and specify that port range in the config. After I did that, I just managed to start a session with three guests w/o any errors logged. I'll try to write up a guide in the next couple of days.

The complete guide would be much appreciated! I tried it out today. I get the same error as you. I opened up three additional ports for udp endpoint and changed the config to:
min-port=...07
max-port=...09

But the error persists.

I also get an error message when trying to enable mysql. I entered: 
mysql-userdb="host=127.0.0.1 dbname=username_coturn password=mysecretpassword"

 Error retrieving MySQL DB information; probably, the tables 'allowed_peer_ip' and/or 'denied_peer_ip' have to be upgraded to include the realm column.

> For testing the configuration I used [WebRTC samples Trickle ICE](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) (with username/password configuration)

Could you explain how to set up users? I always get an error when trying to use stun with jitsi/atalk (xmpp p2p calls). 

Error: "56: check_stun_auth: Cannot find credentials of user"

**Comment by SalocinHB** [comment]
I only used this for Nextcloud Talk, with a long term secret, no users. In order to use MySQL, you need to import `turndb/schema.sql` into your database.

**Comment by beatstick** [comment]
Hi,
I am still getting connection errors for mysql, but the setup works now for xmpp zrtp calls. (It's indeed impossible to set up an auth-secret and multiple users at the same time). Or it did work for a time. Now I am getting the "no available ports 3" error all the time. How many ports did you free up for udp relay? I opened 3, but the standard config seems to be set up for a lot of udp ports. I will try adding a couple more ports.
