### ISSUE TITLE
Switch from drupal-composer/drupal-project to drupal/recommended-project

### ISSUE THREAD

**Issue by jonmz** [Uberspace/lab#588]
At the moment, the Drupal lab guide is based on [Composer template](https://github.com/drupal-composer/drupal-project), doing the installation with this command:

```
composer create-project drupal-composer/drupal-project:8.x-dev drupal --no-interaction
```

Recently, this method of installation stopped working because composer needs over 1,5 GB of memory to resolve all dependencies. Also, [the official docs tell us](https://www.drupal.org/docs/develop/using-composer/using-composer-to-install-drupal-and-manage-dependencies#drupal-composer-drupal-project):

> **Deprecated: Using drupal-composer/drupal-project**
> Using drupal-composer/drupal-project has been deprecated as of Drupal 8.8.0. Please use the officially supported drupal/recommended-project instead, according to the instructions above.

Therefore we should switch the installation method.

**Comment by pheraph** [comment]
I switched to `drupal/core-recommended`, but a `composer update` still gets killed („Getötet“) on U7. So the only way to update is to copy to local, update locally, copy composer.lock to uberspace and remotely execute `composer install`. The php process burns 1.7GB locally, which explains the killing on U7. In this respect, nothing seems to have improved.

**Comment by jonmz** [comment]
> I switched to `drupal/core-recommended`

Did you switch on an existing project or tried it on a fresh one? I just tried the installation on a fresh U7 account and it worked perfectly fine, using only ~241M memory as measured with `/usr/bin/time -v`:

```
[drutest@stardust ~]$ /usr/bin/time -v composer create-project drupal/recommended-project drupal
Creating a "drupal/recommended-project" project at "./drupal"
[...]
	Maximum resident set size (kbytes): 247692
[...]
```
The same goes for an update - even if the memory usage was higher, it was still _way_ below our account-wide limit of 1.5G:
```
[drutest@stardust drupal]$ /usr/bin/time -v composer update drupal/core --with-dependencies
[...]
	Maximum resident set size (kbytes): 634352
[...]
```
If you switched from an already existing project, though, the use of the original template might have already introduced package dependencies that don't go away by switching the base template. Unfortunately I don't know how to solve this (I'm more an admin than a PHP/Drupal developer), but for new installations, using `drupal/core-recommended` still seems to be a correct recommendation to me.
