### ISSUE TITLE
Guide for goaccess: config directory

### ISSUE THREAD

**Issue by philipp-r** [Uberspace/lab#623]
The guide for goaccess has the following command:

`
[isabell@stardust ~]$ cp /etc/goaccess.conf ~/etc/goaccess.conf
`

This is wrong because the config file is located in `/etc/goaccess/goaccess.conf` (at least on kushida.uberspace.de)

**Comment by luto** [comment]
https://github.com/Uberspace/lab/commit/ad6ae59347486931c59501801d26c54069ffb792
