### ISSUE TITLE
Guide for firefly-iii

### ISSUE THREAD

**Issue by shuairan** [Uberspace/lab#626]
Got firefly-iii (https://www.firefly-iii.org/) running on my uberspace and now I'll reproduce the steps and write a guide.

**Comment by mspittler** [comment]
I'd be highly interested

**Comment by FelixKohlen** [comment]
@shuairan are you still working on your version? It has been some time and if you are not working on it anymore, I would publish mine. I recently installed firefly iii and wrote the steps down.

**Comment by gumbi** [comment]
@FelixKohlen I would highly appreciate your guide. I am not able to get Firefly up and running.

**Comment by Systemsemaphore** [comment]
@FelixKohlen @gumbi +1 from me, instructions on how to install (and update?) Firefly in Uberspace would be very helpful
