### ISSUE TITLE
[ghost] timezone bug due to upgrading

### ISSUE THREAD

**Issue by tobimori** [Uberspace/lab#638]
The upgrade script and manual way as described in Uberspace Lab for Ghost breaks an instance and causes a time zone error as seen in this [video](https://www.youtube.com/watch?v=5oEBYSrOu5k).

Issue in Ghost repository: https://github.com/TryGhost/Ghost/issues/11749#issuecomment-619380897

cc @pbeckmann @nowag @nichtmax @SalocinHB @MaluNoPeleke

**Comment by pbeckmann** [comment]
For a repair of my current installations i did:
supervisorctl stop ghost
rm -rf ghost/current/node_modules
npm install -g yarn
yarn install --production
supervisorctl start ghost
Afterwards the error didn’t exists anymore.

Secondly i changed the line in my local copy of the upgrade script from npm install --production to yarn install --production. So the next upgrades don’t break the installations again.

**Comment by tobimori** [comment]
Can confirm replacing npm with yarn fixed the issue. Should be also replaced in the guide. I will do that tomorrow or on Monday, when I find time, if nobody else wants to take that over.

**Comment by tobimori** [comment]
added to guide in pull request #640
