### ISSUE TITLE
Netlify Build fails

### ISSUE THREAD

**Issue by ebroda** [Uberspace/lab#645]
For two (#642, #643) of my three latest PR the netlify build failed. 

[The logs](https://app.netlify.com/sites/uberlab/deploys/5ea952b88430130006fbe326) write:
```
12:11:22 PM: Version '8' not found - try `nvm ls-remote` to browse available versions.
12:11:22 PM: Failed to install node version '8'
```

So probably Node 8 is no longer available in all runners of Netlify and should be updated.

I had a look in the netlify.toml in this repository but there the version is not set.

**Comment by luto** [comment]
it fixed itself, apparently.
