### ISSUE TITLE
nextcloud guide lacks information how to setup email-sending

### ISSUE THREAD

**Issue by cknoll** [Uberspace/lab#674]
I am refering to this guide: https://lab.uberspace.de/guide_nextcloud.html

After some initial success experiences I struggled quite some time to setup the email-sending capability of nextcloud with via smpt of the respective uberspace server. I think the guide should mention this. I had two problems:

1. Finding out which combination of options (sending mode, encryption method, authetification method, ...)  I have to choose.
2. Finding out that the smtp password is the ssh password (which is optional to set).

Suggestsions:
- Add a section "Configuration" before "Tuning",
- mention where the frondend-configuration options can be found
- explicitly mention email-sending capability (important for user-interaction like password-reset)
- linking to https://manual.uberspace.de/mail-access.html#smtp
- giving examples for the configuration values like `isabell@uber.space` and `stardust.uberspace.de` or maybe even insert a screenshot
- update https://manual.uberspace.de/mail-access.html#smtp such that the password-row links to the  warning at the to of the page (ssh password has to be set explicitly)

**Comment by luto** [comment]
https://lab.uberspace.de/guide_nextcloud.html#sendmail-settings
