### ISSUE TITLE
Guide for Jupyter Notebook

### ISSUE THREAD

**Issue by JustusAdam** [Uberspace/lab#684]
I have just successfully deployed jupyter to my Uberspace. It wasn't super difficult but there were a few steps involved and I could write up a short guide on how to do it.

I have seen that there is interest in JupyterHub (#503). I have tried that as well, but it does not seem to work (as of yet) as JupyterHub heavily relies on having root access (sad). However the normal jupyter installation would already allow you to access your notebooks from the outside, but it'd be restricted to single-user (i.e. to share you have to give other people your password)

**Comment by EV21** [comment]
Are you still on it? I could do the guide, if you have not time.

**Comment by JustusAdam** [comment]
Well I never really started, because I got busy with other things. So feel free to go for it, I'd be happy to review it or help out otherwise.
