### ISSUE TITLE
update via git requires configuration

### ISSUE THREAD

**Issue by jeyca** [Uberspace/lab#69]
Some guides advise to update via `git pull ...` but that fails when there is no name/email configured for git. Should this problem be explained somehow or can we trust in the users that they understand the elaborate error message ?

```
From https://github.com/user/software
 * branch              master     -> FETCH_HEAD

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <isabell@stardust.uberspace.de>) not allowed
```

**Comment by nichtmax** [comment]
I think this is self-explaining. When there are lots of users asking about this, we'll include it.
