### ISSUE TITLE
problems installing mailman3

### ISSUE THREAD

**Issue by ezzra** [Uberspace/lab#704]
I encountered problems while using the guide for mailman3. The packages installation

    pip3.6 install --user mailman hyperkitty postorius mailman-hyperkitty whoosh

failed with package `fufl.lock` why I chose to use `pip3.7` instead (also because its the lts version and should be used anyway) That worked, but now I run into problems with 

    $ python3.7 manage.py migrate
    ImportError: cannot import name 'six' from 'django.utils' (/home/USER/.local/lib/python3.7/site-packages/django/utils/__init__.py)

I guess this is something based on django and python package dependencies, I unfortunately just have not the time to investigate here more but wanted to report it for others or later. So far, I guess the guide is not working as it is now.

**Comment by ezzra** [comment]
and of course I would be happy if someone else can find the corrections ;) maybe @rikroe or @pheraph can help again

**Comment by noave** [comment]
there is a fix in #763 

spoiler: just use `python/pip3.8` :)

**Comment by noave** [comment]
fixed in #772
