### ISSUE TITLE
CouchDB guide

### ISSUE THREAD

**Issue by SalocinHB** [Uberspace/lab#705]
[Installation from source](https://docs.couchdb.org/en/stable/install/unix.html#installation-from-source) should be possible as soon as the `js` RPM is installed on U7 hosts.

**Comment by ragchuck** [comment]
any plans when this will be available?

**Comment by ragchuck** [comment]
These are my very first steps into working with Github and collaborating with others. So bear with me if I do something wrong and let me know...

During the last days, I tried to install [CouchDB ](https://formulae.brew.sh/formula/couchdb)with [homebrew/linuxbrew](https://docs.brew.sh/Homebrew-on-Linux) but without any success. :(
After many attempts fixing some compilation issues related to the Uberspace environment and Erlang installation I could finally build CouchDB, but unfortunately it's not working because of a library Issue:
`"/lib64/libc.so.6: version GLIBC_2.18' not found (required by /home/ragchuck/.linuxbrew/lib/libstdc++.so.6)"`

I installed glibc-2.23 via homebrew before compiling, but CouchDB is somehow pointing to the Host glib, which is still 2.17.
_I think this could also be an issue with the RPM installation - I just wanted to point that out._

I learned a lot during these days of installing one dependency after another and falling into issues in almost every step.

As said this is my first comment in this project and this Issue is tagged with (**help wanted**). So, I would like to offer my help if you want: I would write a Guide once I managed to successfully install an working CouchDB instance.

I'd like to know if the **js** RPM will be installed on U7 hosts until end of the year?

I'm hosting a project for my dad on my Uberspace 6 account, which is relying on CouchDB. So it's important for me to have this feature also in U7, which I would like to migrate until end of the year.

Best Regards....

**Comment by SalocinHB** [comment]
Please don't use Linuxbrew unless you know what you're doing. Replacing GLIBC with a self-compiled version is bound to get you in trouble.

**Comment by SalocinHB** [comment]
> I'd like to know if the js RPM will be installed on U7 hosts until end of the year?

Yes, should be available with the next release. Keep an eye on the [changelog](https://manual.uberspace.de/changelog.html).

**Comment by alpcoder** [comment]
We could include data migration steps in this lab guide as well. Long story short: Best way to migrate from CouchDB 1.5. (as some instances are still on this version in U6) to CouchDb 3.X is to setup a replication between them and let 3.X pull.

**Comment by alpcoder** [comment]
@SalocinHB do you have an update on this? In the changelog its says js is now installed, would that mean installation from source should be possible? Thanks!

**Comment by SalocinHB** [comment]
Turns out, it needs js-devel as well, sorry. Will be installed soon™

**Comment by ragchuck** [comment]
I've managed to install CouchDB using  **yumdownloader** and **rpm2cpio** in July. still running without any issues. :)
Thanks to @alpcoder with your hint to let 3.X pull data, worked as a charm to migrate the data...

**Comment by alpcoder** [comment]
@ragchuck would you be able to provide some more detailed instructions? From your and my experience we then could create a lab guide. Bit in a hurry in this now since uberspace 6 will shut down soon. :-)

**Comment by alpcoder** [comment]
This is how far I get: 

`
mkdir couchdb

cd couchdb

yumdownloader install autoconf autoconf-archive automake \
    curl-devel erlang-asn1 erlang-erts erlang-eunit gcc-c++ \
    erlang-os_mon erlang-xmerl erlang-erl_interface help2man \
    js-devel-1.8.5 libicu-devel libtool perl-Test-Harness

wget "https://apache.lauf-forum.at/couchdb/source/3.1.1/apache-couchdb-3.1.1.tar.gz"

tar -zxvf apache-couchdb-3.1.1.tar.gz

cd apache-couchdb-3.1.1

./configure

# Success

make release

**********************************************************************
This version of Erlang ("21.0") is known to contain bugs that directly
affect the correctness of Apache CouchDB.

You should *NOT* use this version of Erlang.

See https://docs.couchdb.org/en/stable/install/unix.html#dependencies
for the latest information on dependencies.
*********************************************************************`

**Comment by ragchuck** [comment]
@alpcoder I did some notes while I was installing (no guaranty for completeness 😏):

hope this helps...

## Create rpm directory & rpm ini file for CouchDB 

	mkdir -p ~/rpm
	vi ~/rpm/apache-couchdb-rpm.ini

> 	```
> 	[bintray--apache-couchdb-rpm]
> 	name=bintray--apache-couchdb-rpm
> 	baseurl=http://apache.bintray.com/couchdb-rpm/el$releasever/$basearch/
> 	gpgcheck=0
> 	repo_gpgcheck=0
> 	enabled=1

## Download CouchDB + dependencies

	yumdownloader --destdir ~/rpm --resolve couchdb -c ~/rpm/apache-couchdb-rpm.ini


## Create yum directory for CouchDB & Extract rpm files

	mkdir ~/yum && cd ~/yum
	rpm2cpio ~/rpm/couch*.rpm | cpio -id


## Add CouchDB to PATH + LD_LIBRARY_PATH
	vi ~/.bash_profile

> 	```
> 	export PATH=$HOME/yum/opt/couchdb/bin:$HOME/.local/bin:$HOME/bin:$PATH
> 	export LD_LIBRARY_PATH="/lib:/lib64:$HOME/yum/usr/lib:$HOME/yum/usr/lib64"



## Create local config file
	cp $HOME/yum/opt/couchdb/etc/local.ini ~/couchdb-3.1.0.ini

## Create CouchDB directories in home for data files
	mkdir -p ~/couchdb-3.1.0/data
	mkdir -p ~/couchdb-3.1.0/index

## Add admin user + directories
`single_node=true` is important

	vi  ~/couchdb-3.1.0.ini

> 	```
>	[couchdb]
>	single_node=true
>	;max_document_size = 4294967296 ; bytes
>	;os_process_timeout = 5000
>	database_dir = <home>/couchdb-3.1.0/data
>	view_index_dir = <home>/couchdb-3.1.0/index
> 	
>	[chttpd]
>	port = 5984
>	bind_address = 0.0.0.0


## Add uberspace web backend for couchdb
	uberspace web backend set /couchdb --http --port 5984 --remove-prefix


## Test everything works, cancel with CTRL+C
	couchdb -couch_ini $HOME/yum/opt/couchdb/etc/default.ini $HOME/couchdb-3.1.0.ini


## Add supervisord service
	vi ~/etc/services.d/my-couchdb.ini

> 	```
>	[program:my-couchdb]
>	command = couchdb -couch_ini %(ENV_HOME)s/yum/opt/couchdb/etc/default.ini %(ENV_HOME)s/couchdb-3.1.0.ini
>	autostart = yes
>	autorestart = yes
>	environment = PATH="%(ENV_HOME)s/yum/opt/couchdb/bin:%(ENV_PATH)s",LD_LIBRARY_PATH="/lib:/lib64:%(ENV_HOME)s/yum/usr/lib:%(ENV_HOME)s/yum/usr/lib64"
>	stdout_logfile = %(ENV_HOME)s/logs/my-couchdb.log
>	stderr_logfile = %(ENV_HOME)s/logs/my-couchdb.log

## Start CouchDB via supervisorctl
	supervisorctl reread
	supervisorctl start my-couchdb

## Check if running
 	tail -f ~/logs/couchdb.log

DONE! 🛩️

**Comment by luto** [comment]
FYI: we'll pre-install couchdb-binaries in a future release, which should make this a lot easier.

**Comment by janl** [comment]
@luto couchdb project lead (and uberspace customer) here, if you need any advice on that, or would like a review of how you're doing all that, feel free to get in touch: jan@apache.org

**Comment by alpcoder** [comment]
Thank you @ragchuck! 
Few additions for clarity maybe: 
1) After adding couchdb to bash profile we need to 
`source ~/.bash_profile`
2) Admin is added at the end of the file. See: https://docs.couchdb.org/en/stable/config/auth.html#config-admins
3) On the "testing" step we can add to call the Front-End via 
https://uberspaceusername.uber.space/couchdb/_utils/
4) At the end (optional) data migration with replication from remote "old" host

**Comment by alpcoder** [comment]
One question remains for me, and maybe @janl and somebody from uberspace (@luto ?) can chip in here: From your "local" application e.g. php script, how would you reach and authenticate with the database (assuming it's running on the same host). First, would you be able to use localhost? Second, what about port configuration say for example multiple users are using on the same host couchdb? Do I understand correct (a bit hidden here: https://manual.uberspace.de/background-network.html#impact-on-users) that I have my own 127.0.0.1 and can choose any port I like and then would use for internal traffic $USERNAME.local.uberspace.de:5984 ?

**Comment by luto** [comment]
> First, would you be able to use localhost?

yes.

> Second, what about port configuration say for example multiple users are using on the same host couchdb?

Communication between users is not supported. If you'd like to expose your couchdb to other multiple users, either setup an SSH tunnel, [open a port in the firewall](https://manual.uberspace.de/basics-ports.html) or even expose it via [our web server](https://manual.uberspace.de/web-backends.html) (couchdb uses HTTP(S) under the hood, I think).

**Comment by alpcoder** [comment]
On the second aspect, I was making myself not clear. From what I understand two users would (independent from each other) run a couchdb on their localhost port 5984, correct? 
Reason I am asking: In uberspace 6, from what I understand, every instance needed its own port.

**Comment by luto** [comment]
Yes, each user gets their own localhost and therefore their own localhost port 5984.

**Comment by ragchuck** [comment]
@alpcoder thank you for your review comments! 👍 
soo... we'll wait until the couchdb binaries are available in the one of the next releases?
I don't think it makes much sense to publish our guide now, when the uberspace team provides the binaries soon... 
So this cumbersome installation wouldn't be necessary anymore... What do you think? @alpcoder , @luto, @SalocinHB

**Comment by alpcoder** [comment]
@ragchuck I would agree. 
@luto  is there a timeline to the release of couchdb on uberspace 7? Will this be before uberspace 6 shutdown?

**Comment by luto** [comment]
@ragchuck couch will probably land in the next release. Are you up for creating a guide? :) You can expect the binaries to sit in `/usr/bin/` like all the other ones. So you don't need to provide a path at all: `command=couchdb ...`.

**Comment by luto** [comment]
CouchDB binaries are now available: https://manual.uberspace.de/database-couchdb/

is anyone up for writing a guide? :)

**Comment by dotWee** [comment]
@luto I've just pushed my draft for CouchDB and created a pull request (see https://github.com/Uberspace/lab/pull/959).
