### ISSUE TITLE
[nextcloud] Command "db:add-missing-columns" is not defined.

### ISSUE THREAD

**Issue by taddydevil** [Uberspace/lab#728]
Got following error when running manually ```php occ db:add-missing-columns``` from the update script with the version 18.0.6:
```
  Command "db:add-missing-columns" is not defined.

  Did you mean one of these?
      db:add-missing-indices
      db:convert-filecache-bigint
      db:convert-mysql-charset
      db:convert-type
```

Is this only available in version 19?

EDIT: There are also some building errors. Needs only an additional empty line:

```
lab-master\source\guide_nextcloud.rst:240: WARNING: Unexpected indentation.
lab-master\source\guide_nextcloud.rst:251: WARNING: Unexpected indentation.
lab-master\source\guide_nextcloud.rst:270: WARNING: Unexpected indentation.
```

**Comment by EV21** [comment]
You're right, I didn't think about that when I add the script.

With Nextcloud 19 the following commands are possible.
```
db:add-missing-columns          
db:add-missing-indices          
db:convert-filecache-bigint     
db:convert-mysql-charset        
db:convert-type                 
maintenance:mimetype:update-db
```

**Comment by taddydevil** [comment]
I suggest to add an note because version 18 is in the stable channel and I think most users still use the stable channel and the error confuse people like me 😆

**Comment by EV21** [comment]
The warning is very dominant. We can comment that line out with an additional note.
```
#The following command works from Nextcloud 19
#db:add-missing-columns
```

**Comment by taddydevil** [comment]
Love it.
