### ISSUE TITLE
add a guide for pretix

### ISSUE THREAD

**Issue by luto** [Uberspace/lab#74]
[Pretix](https://pretix.eu/) is a popular opensource ticketing solution. It can be used to sell tickets for workshops, events or even just limit the number of people for a free event. Being a django application it is fairly easy to deploy. There is an [existing, recent guide](https://bullenscheisse.de/2018/pretix-auf-einem-uberspace/) for U6. Kindly ask the author for permission, credit them in the guide, port it to U7 and replace sqlite with mysql.

**Comment by digitalesIch** [comment]
@ezzra ping

**Comment by smokephil** [comment]
@ezzra ping

**Comment by ezzra** [comment]
ok yeah :) I just have successfully set up a new clean installation according to the styleguide rules. I still need to process the dirty notes to a pretty nice well formed installation guide. I think I'll have this done by the next days.

**Comment by ezzra** [comment]
@digitalesIch @smokephil  ok its merged!

**Comment by benrichit** [comment]
> @digitalesIch @smokephil ok its merged!
Can anyone tell me how to install plugins on Uberspace?
For example https://marketplace.pretix.eu/products/passbook/instructions
