### ISSUE TITLE
rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by SalocinHB** [Uberspace/lab#750]
See https://github.com/github/renaming

**Comment by luto** [comment]
also change the "production branch" [inside the netlify settings](https://app.netlify.com/sites/uberlab/settings/deploys) accordingly.

**Comment by luto** [comment]
Github is working on a feature to make this easy and seamless, so I guess we'll wait for a bit.

**Comment by EV21** [comment]
The renaming feature has been released (globally) a few hours ago.
Pull requests will also be automatically re-targeted as I can see in my private test repo.
![grafik](https://user-images.githubusercontent.com/8345730/104790152-0d50a800-5797-11eb-9ccf-ef45b042a89a.png)

**Comment by luto** [comment]
thanks for the heads-up. done.
