### ISSUE TITLE
PR policy: single commit + force-push?

### ISSUE THREAD

**Issue by jorsn** [Uberspace/lab#769]
Is there some policy how changes to PRs shall be added, e.g. from the PR review? Amend and force-push? Append and squash?
Also: Shall a PR have only one commit in general?

**Comment by EV21** [comment]
While many PRs are WIP and it is more easy to follow the progress e.g. after a review, change request or reverting single changes it's more common to have more commits, especially when collaborating with more devs. 

I know from other project the policy to squash-merge PRs when it's done (that would be done by a responsible person like @luto in this case). So many commits will be rebased into a single one at master/main to have a nice and clean commit history with one commit per feature. The many commits will still be available in the closed PR to follow to progression history. 

![grafik](https://user-images.githubusercontent.com/8345730/95010100-04dcc300-0627-11eb-81d4-76bdb81a59f5.png)

**Comment by luto** [comment]
We'll do this depending on the commits in the request.
