### ISSUE TITLE
Deployment information for React & 404 error

### ISSUE THREAD

**Issue by crevulus** [Uberspace/lab#790]
What are the guidelines for deploying a react frontend? Following advice from Nico and Michael (as well as your docs), I've moved the build folder into /home/{user}/html. However, visiting the site throws a 404. Even putting a simple index.html file in there throws a 404.

Is there a preferred directory structure for my React build folder?

**Comment by luto** [comment]
This seems like a problem specific to your installation. Please ping hallo@uberspace.de, if this is still relevant.
