### ISSUE TITLE
Guideline for multiple supervisord services (priority)

### ISSUE THREAD

**Issue by sunflower-seed** [Uberspace/lab#814]
Some services created in the lab require different services to be managed by supervisord.

E.g. MongoDB and a Node Application.

Of course you want to have the DB started before the application.

Supervisord provides a priority feature and a subprocess feature.

Every Guide in the lab  that uses more than one service on the (empty) uberspace should be updated for priority or otherwise there should be a hint in the manual that supervisord has this features as they might be important on restarts.

**Comment by luto** [comment]
By default supervisord restarts failed services up to three times before actually giving up. This gives MongoDB enough time to boot while node is trying to connect. I don't know of any real word support cases where this has caused a problem.

**Comment by sunflower-seed** [comment]
https://twitter.com/ubernauten/status/1324685881924636673

Maybe you are right but still some confusion around as i see in tweet replies

**Comment by luto** [comment]
Which reply are you referring to? The replies only seem to confused whether they are using supervisord services at all, not about the interplay of multiple services.

**Comment by sunflower-seed** [comment]
ok
