### ISSUE TITLE
[bitwarden_rs] data folder and clearer instructions for web vault

### ISSUE THREAD

**Issue by thurti** [Uberspace/lab#843]
I followed the guide but I had to add the `bitwarden_rs/data` folder manualy. Otherwise the bitwarden server crashed with "error creating keys". Maybe this step should be added to the guide?

Another thing I struggled with was the following note regarding the web vault:

> If you don't want to use the web-vault feature (web-app access to your vaults) for any security reasons you can skip this step.

It should be more clear that without the web app an invited user can't join because the link sent with the invitation mail leads to a 404 site. Or is there any other way to add a user?

**Comment by schulzemic** [comment]
Thank you for the information about adding the folder. It drove me nuts!
