### ISSUE TITLE
[coturn] most of the time installations don't work

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/lab#844]
In our experience in support, the guide only works sometimes and often does not work. We can only roughly isolate the problem and assume that it has something to do with the number of ports used.

Guides that only work sometimes and sometimes don't work do not provide a good experience for the users. If it's not clear why they don't work and the logs don't provide enough information we can't support users and the guide has to be removed.

@jo-mei as this is your guide do you have any idea how to go forward or add information to help debugging?

**Comment by nichtmax** [comment]
https://github.com/Uberspace/lab/pull/845

**Comment by alangecker** [comment]
I had now issues as well, but managed to get it into a working state.

For me it was the issue _4.5.2 starting up got stuck_ https://github.com/coturn/coturn/issues/683, which got resolved with https://github.com/coturn/coturn/pull/684 and will be part of the upcoming `4.5.3` release.

Unfortunately building the current master on the uberspace7 (centos7) doesn't work out of the box:
```
in function `replace_one_ssl_ctx':
undefined reference to `SSL_CTX_up_ref'
```

but with manually specifying the libssl version to `1.1.1` I was able to at least build the `turnserver`

```
export SSL_LIBS="-l:libssl.so.1.1 -l:libcrypto.so.1.1"
export SSL_CFLAGS="-I/havetobedefinedtosomething"
./configure --prefix=/home/USER/opt/turnserver
make bin/turnserver
```

this is definitely too hacky for a nice guide, but the old guide might work again with `4.5.3` and maybe it helps now someone here 😄
