### ISSUE TITLE
[Nextcloud] Disable backups before update via  ~/bin/nextcloud-update script

### ISSUE THREAD

**Issue by beatstick** [Uberspace/lab#851]
There is already an update script and a workaround for storage capacity problems in the uberspace documentation. 
I think it would be best to disable the automatic backups that the nextcloud updater generates as they are really not needed on the uberspace and take up unnecessary time and resources. 

The updater provides no flag to disable automatic backups, so the only workaround at the moment seems to edit the nextcloud/updater/index.php. 

Three lines need to be commented out:
//	case 3:
//		$updater->createBackup();
//		break;

Cmp.: https://github.com/nextcloud/updater/issues/145#issuecomment-612727675

I think this could be handled by issuing a sed command during the nextcloud-update script on uberspace.

**Comment by beatstick** [comment]
Thanks @EV21. This works for me. 

My advice would be to change the update script (~/bin/nextcloud-update) as follows:

---------------------------------------------------------------

# Updater automatically works in maintenance:mode

#option 1: create backup before updating (use option 1 or 2, not both)
php ~/html/updater/updater.phar --no-interaction

#option 2: don't create backup before updating
#php ~/html/updater/updater.phar --no-interaction --no-backup

# re-enable maintenance mode for occ commands
php ~/html/occ maintenance:mode --on

## database optimizations
## The following command works from Nextcloud 19.
## remove '#' so it is working
#php ~/html/occ db:add-missing-columns
php ~/html/occ db:add-missing-indices
php ~/html/occ db:convert-filecache-bigint

php ~/html/occ app:update --all
php ~/html/occ maintenance:mode --off
restorecon -R ~/html

-----------------------------
I tested it and it works for me

**Comment by EV21** [comment]
> I tested it and it works for me

Thank you, it's is also working for me since the guys from nextcloud fixed their server issues.

Since (as of my knowledge) the updater only backups the code files there is no need for a second option, so I just set `--no-backup` as default. The Uberspace backup system does all we need and the users should use another external script for saving their files outside of uberspace.

**Comment by beatstick** [comment]
Fair enough. Thanks a lot for the fix.
