### ISSUE TITLE
guide for hedgedoc (formerly codimd / hackmd)

### ISSUE THREAD

**Issue by noave** [Uberspace/lab#876]
https://github.com/hedgedoc/hedgedoc

who wants to create a guide :)

**Comment by Systemsemaphore** [comment]
I followed the [manual installation guide](https://github.com/hedgedoc/hedgedoc/blob/master/docs/setup/manual-setup.md) and was able to start the server. After creating a web backend and accessing the url, I got a 502 - Bad Gateway.

Hedgedoc log:

`yarn run v1.22.5
$ sequelize db:migrate && node app.js

Sequelize CLI [Node: 10.23.0, CLI: 5.5.1, ORM: 5.22.3]

Parsed url mysql://hedgedoc:*****@localhost:3306/hedgedoc_db
No migrations were executed, database schema was already up to date.
(...)
2020-12-11T23:32:19.674Z info:  HTTP Server listening at 0.0.0.0:3000
Error: Could not find the include file "../build/cover-header"
    at getIncludePath (/home/hedgedoc/hedgedoc/node_modules/ejs/lib/ejs.js:165:13)
    at includeSource (/home/hedgedoc/hedgedoc/node_modules/ejs/lib/ejs.js:309:17)
    at /home/hedgedoc/hedgedoc/node_modules/ejs/lib/ejs.js:745:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/home/hedgedoc/hedgedoc/node_modules/ejs/lib/ejs.js:721:15)
    at includeSource (/home/hedgedoc/hedgedoc/node_modules/ejs/lib/ejs.js:313:9)
    at /home/hedgedoc/hedgedoc/node_modules/ejs/lib/ejs.js:745:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/home/hedgedoc/hedgedoc/node_modules/ejs/lib/ejs.js:721:15)
    at Template.compile (/home/hedgedoc/hedgedoc/node_modules/ejs/lib/ejs.js:574:12)
    at Object.compile (/home/hedgedoc/hedgedoc/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/home/hedgedoc/hedgedoc/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/home/hedgedoc/hedgedoc/node_modules/ejs/lib/ejs.js:254:16)
    at View.exports.renderFile [as engine] (/home/hedgedoc/hedgedoc/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (/home/hedgedoc/hedgedoc/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/hedgedoc/hedgedoc/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/hedgedoc/hedgedoc/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/hedgedoc/hedgedoc/node_modules/express/lib/response.js:1012:7)
    at showIndex (/home/hedgedoc/hedgedoc/lib/response.js:47:9)
    at Layer.handle [as handle_request] (/home/hedgedoc/hedgedoc/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/hedgedoc/hedgedoc/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/hedgedoc/hedgedoc/node_modules/express/lib/router/route.js:112:3)`

For me, this looks like the frontend bundle is missing, even though it shouldn't*

> Our release tarballs now contain the frontend bundle. This saves users from building the frontend themselves, which was an issue on memory-constrained systems.

*see [https://github.com/hedgedoc/hedgedoc/releases/tag/1.7.0-rc1](https://github.com/hedgedoc/hedgedoc/releases/tag/1.7.0-rc1)

So I tried again, this time not skipping step 5 of the manual installation guide, but actually running

`yarn run build`

I've waited for 60+ minutes for this to complete. It did not. I'm stumped. Help would be appreciated.

**Comment by EV21** [comment]
It worked for me (without building)🚀 

```bash
[isabell@stardust ~]$ uberspace tools version use node 14
Selected node version 14
The new configuration is adapted immediately. Patch updates will be applied automatically.
[isabell@stardust ~]$ mysql -e "CREATE DATABASE ${USER}_hedgedoc"
[isabell@stardust ~]$ VERSION=1.7.0-rc2
[isabell@stardust ~]$ wget https://github.com/hedgedoc/hedgedoc/releases/download/$VERSION/hedgedoc-$VERSION.tar.gz
[...]
[isabell@stardust ~]$ tar --extract --gzip --file=hedgedoc-$VERSION.tar.gz
[isabell@stardust ~]$ rm hedgedoc-$VERSION.tar.gz
[isabell@stardust ~]$ hedgedoc/bin/setup
[...]
[isabell@stardust ~]$ rm hedgedoc/config.json
[isabell@stardust ~]$
```
Create `~/hedgedoc/config.json` with the following content:
```json
{
    "production": {
        "domain": "isabell.uber.space",
        "loglevel": "info",
        "cookiePolicy": "lax",
        "sessionSecret": "SamethingSuperRANDOM",
        "db": {
            "username": "isabell",
            "password": "YourMySQL-Password",
            "database": "isabell_hedgedoc",
            "host": "localhost",
            "port": "3306",
            "dialect": "mysql"
        },
        "linkifyHeaderStyle": "gfm"
    }
}
```
Edit the file `~/hedgedoc/.sequelizerc` with the following content:
```js
var path = require('path');

module.exports = {
    'config':          path.resolve('config.json'),
    'migrations-path': path.resolve('lib', 'migrations'),
    'models-path':     path.resolve('lib', 'models'),
    'url':             'mysql://isabell:YourMySQL-Password@localhost:3306/isabell_hedgedoc'
}
```
Try to start the server:
```bash
[isabell@stardust ~]$ cd hedgedoc
[isabell@stardust hedgedoc]$ NODE_ENV=production yarn start
yarn run v1.22.5
$ sequelize db:migrate && node app.js

Sequelize CLI [Node: 14.15.0, CLI: 5.5.1, ORM: 5.22.3]

Parsed url mysql://isabell:*****@localhost:3306/isabell_hedgedoc
No migrations were executed, database schema was already up to date.
2020-12-15T15:40:56.420Z info:  HTTP Server listening at 0.0.0.0:3000
```
```bash
[isabell@stardust ~]$ uberspace web backend set / --http --port 3000
Set backend for / to port 3000; please make sure something is listening!
You can always check the status of your backend using "uberspace web backend list".
[isabell@stardust ~]$ $ uberspace web backend list
/ http:3000 => OK, listening: PID 27717, /opt/nodejs14/bin/node app.js
```
Than you can setup the supervisord service and that's it. (🛠️ TODO)

**Comment by Systemsemaphore** [comment]
Yep, those were basically the steps I took but I went with Node 10 instead. That might explain the problems I had.

With Node 14, after starting the server and creating the web backend, I can actually access the page, but the layout looks... broken?

![Screenshot 1](https://user-images.githubusercontent.com/74195074/102264982-b006d400-3f16-11eb-9e02-d51d6708c5f6.PNG)

![Screenshot 2](https://user-images.githubusercontent.com/74195074/102265013-bac16900-3f16-11eb-88f7-d1d0b076d5e6.PNG)

**Setup the supervisord service**

1. Create `~/etc/services.d/hedgedoc.ini` with the following content:

```
[program:hedgedoc]
directory=/home/hedgedoc/hedgedoc
command=env NODE_ENV=production yarn start
autostart=yes
autorestart=yes
```

2. After creating the configuration, tell supervisord to refresh its configuration and start the service:

```
[isabell@stardust ~]$ supervisorctl start hedgedoc
hedgedoc: started
[isabell@stardust ~]$ supervisorctl stop hedgedoc
hedgedoc: stopped
[isabell@stardust ~]$ supervisorctl restart hedgedoc
hedgedoc: stopped
hedgedoc: started
```

I don't know what to do about the broken layout, can somebody confirm or deny? Anyway, these should be all the necessary steps for a guide.

**Comment by EV21** [comment]
Does the configured domain match?
While I was playing around with the config settings it (the broken layout) happened when I misses some letters.

**Comment by Systemsemaphore** [comment]
Nice catch. No dice though. Copied URL from browser to CLI, restartet the service, layout still broken. You can take a look here: https://hedgedoc.uber.space/

**Comment by EV21** [comment]
I see, but I don't know what is the problem right now. - Have you tried it on a new uberspace?

I think this is better (without isabell)
```ini
[program:hedgedoc]
directory=%(ENV_HOME)s/hedgedoc
command=env NODE_ENV=production yarn start
autostart=yes
autorestart=yes
```

**Comment by Systemsemaphore** [comment]
Whoa, crazy. Tried your link with IE, Chrome, Firefox: Same broken layout in all three browsers. Is my OS the problem? Now I'm curious. Booting Linux, gotta check this.

**Comment by EV21** [comment]
right now your https://hedgedoc.uber.space/ looks perfect to me, nice layout

**Comment by Systemsemaphore** [comment]
I'm going insane 😱 
Linux Notebook: same problem, layout is broken 😕 
pi-hole disabled, dark reader disabled, no script blockers in use

But if it looks fine for you, I guess I'll just go to sleep and take another look at this tomorrow. Thanks for your help!

**Comment by EV21** [comment]
Ok, I noticed suddenly when I tried it on Chrome (usually I am on Firefox) the layouts on my on your instance are broken too.

**Comment by EV21** [comment]
I initially followed [the reverse proxy guide](https://github.com/hedgedoc/hedgedoc/blob/master/docs/setup/reverse-proxy.md#using-a-reverse-proxy-with-hedgedoc) and partly the [full config guide](https://github.com/hedgedoc/hedgedoc/blob/master/docs/configuration.md). Then I deleted all unnecessary (defualt) options in the config file.

I think I figured it out. - Delete `"domain": "isabell.uber.space",` from `config.json` and it might work. 
I tried it with localhost but then it crashes all the time and I needed to manually kill some processes. 
You will get some warnings in the log, but at least it is working (I hope so for you).

don't care warnings: (default settings will be used)
```
2020-12-15T21:36:06.089Z warn: 	Neither 'domain' nor 'CMD_DOMAIN' is configured. This can cause issues with various components.
Hint: Make sure 'protocolUseSSL' and 'urlAddPort' or 'CMD_PROTOCOL_USESSL' and 'CMD_URL_ADDPORT' are configured properly.
```

**Comment by Systemsemaphore** [comment]
That was it. Removed `"domain": "isabell.uber.space",` from `config.json` and the layout looks fine now. It seems Hedgedoc itself and the documentation are still under heavy development. In my opinion, right now the documentation is abysmal and Hedgedoc is bound to generate unnecessary support tickets if the uberlab guide is outdated after every new release. We have all the necessary steps to write and commit `guide_hedgedoc.rst` but I'm not entirely sure about the timing 😞

**Comment by EV21** [comment]
@Systemsemaphore 
deploy preview: [guide_hedgedoc.html](https://deploy-preview-883--uberlab.netlify.app/guide_hedgedoc.html) 
I changed the config using environment variables and also disable user registration as people usually don't want random strangers to use their service.

**Comment by EV21** [comment]
Actually the config file might be smaller than I thought. - The only problem is that if you want to run the command `manage_users`  you previously also have to set the ENV as there would be no information about the database.

`CMD_DB_URL="mysql://isabell:YourMySQL-Password@localhost:3306/isabell_hedgedoc"`

Later when 2.0 is out this should be easy by simply using .env files in the app root directory.

---
.sequelizerc
```jsx=
var path = require('path');

module.exports = {
    'config':          path.resolve('config.json'),
    'migrations-path': path.resolve('lib', 'migrations'),
    'models-path':     path.resolve('lib', 'models'),
    'url':             process.env.CMD_DB_URL
}
```
---
config.json
```json=
{}
```
