### ISSUE TITLE
Baikal issues/rework & improvements

### ISSUE THREAD

**Issue by biolauri** [Uberspace/lab#877]
I've recently used the Baikal guide but stumbled upon a few things. This issue is a collector for it and it's meant as a discussion for some ideas for improvement.

I'd like to add a PR on this, but, unfortunately, can't say when I've got the time for it (hopefully between Christmas & New Year). If anyone else wants to chime in, I'd be more than happy! :)

## Issues
* **Installation**: Update `rmdir html` to `rm -rf html` due to [added default `nocontent.html`](https://manual.uberspace.de/changelog_archive/#v7-7-8
)
* **Updates**: Last sentence doesn't reflect the install location (the `html` path is wrong for the recommended way of installing)
* **_Footer_**: Link to the Baikal website is not official and very outdated (see sabre-io/Baikal#991)

## Changes
* **_Footer_**: I've tested it with Baikal 0.7.2 Uberspace 7.8.0

## Improvements
* **Installation**: Add link to latest release in GitHub and mention how to retrieve the url for `wget`; use the currently latest version in code sample
* **Installation**: Add short comparison between two suggested installation locations (move DocRoot to `baikal/html` vs _install_ Baikal within DocRoot)
  - No other applications on HTTPS (contra DocRoot move)
  - More secure installation (pro DocRoot move)
* Add hints on how to ease up adding a calendar via
  - SRV records, if used with an own domain (see [official docs of sabre.io/dav on Service Discovery](https://sabre.io/dav/service-discovery/))
  - `.well-known` URLs (secretly hidden on [official docs about troubleshooting](https://sabre.io/baikal/troubleshooting/#can%27t-connect-with-os-x-yosemite))
* Add hint for troubleshooting connection problems with iOS devices (I found a helpful [blog article about iOS Baikal problems](https://homan.ee/en/iphone-calendar-synchronization-ios-settings-for-baikal-caldav))

**Comment by biolauri** [comment]
I just found a conflict with the [style guide](https://github.com/Uberspace/lab/blob/master/STYLE.md):  
> Always assume the document root is empty.

I very much like the _Keep it simple_ approach, but since [U7.7.8](https://manual.uberspace.de/changelog_archive/#v7-7-8), the document root is not empty on new Uberspaces. I assume that this _Keep it simple_ approach is especially for users being new to shells/command lines, so it'll be very confusing for them that commands mentioned in these Uberlab guides won't work on their fresh Uberspaces. Therefor, I think it'd be better to drop the sentence cited above from the style guide.

**Comment by thomas-kammerer** [comment]
Just fixed the errors and updated the package versions https://github.com/Uberspace/lab/pull/898

Didn't find the time yet to look at your improvements :-)

**Comment by luto** [comment]
Some of this is outdated and most of it is fixed. Please open individual, small issues for anything that's still broken. Thanks!
