### ISSUE TITLE
[seafile] Update Seafile guide to match latest version (Seafile 7.1)

### ISSUE THREAD

**Issue by biolauri** [Uberspace/lab#881]
I've recently used the Seafile guide but stumbled upon a few things as I tried to use it with the latest version (7.1), but the guide is tested with some 6.x version. This issue is a collector for it and it's meant as a discussion for some ideas for improvement.

I'd like to add a PR on this, but, unfortunately, can't say when I've got the time for it (hopefully between Christmas & New Year). If anyone else wants to chime in, I'd be more than happy! :)

## Issues
* **Installation: Step 2**: Seafile 7.1 needs more dependencies installed via Pip (see [official installation guide](https://manual.seafile.com/deploy/using_mysql/))

## Changes
* **_General**: I've used `python3.8`, so I had to link `python3` to 3.8. I can totally understand if it would be better for the guide to work w/o it, but I didn't test it with 3.6 (where `python3` currently points to)
* Move Installation steps 5 and above to new section **Configuration**
* **_Footer_**: I've tested it with Seafile 7.1.5 on Uberspace 7.8.0

## Improvements
* **Installation: Step 1**: Add link to latest release
* **Configuration**: Adapt it to the config files from latest Seafile version
* **_Configuration: Setup Daemon_**: The guide currently doesn't configure a daemon. I feel like the daemon config would be very nice here, but I've got no clue on Python; would it simply be done with `./seahub.sh restart` & `./seafile.sh restart`? (Of course w/ the correct paths)
  Maybe the [official guide on starting Seafile at bootup](https://manual.seafile.com/deploy/start_seafile_at_system_bootup/) helps
* **Tuning**: It's possible to use memcached for Seafile, but I didn't manage to get the necessary `pylibmc` dependency installed (using [Memcached Uberlab guide](https://lab.uberspace.de/guide_memcached.html)); it'd be very cool to have it: If someone wants to help, let's discuss it here, how to do it
  See [official guide on how to add Memcached to Seafile](https://manual.seafile.com/deploy/add_memcached/)
* **Tuning**: I will enable WebDAV access for my Seafile instance, so I'll add this to the guide, too
  See [official guide on WebDAV extension](https://manual.seafile.com/extension/webdav/)

---

I'll just link the official guides which helped me a lot:
* [Installing Seafile Server manually with MySQL](https://manual.seafile.com/deploy/using_mysql/)
* [Settings for Seahub with Nginx/Uberspace Web Backends](https://manual.seafile.com/deploy/deploy_with_nginx/#modify-ccnetconf-and-seahub_settingpy)
* [Overview of Seahub settings](https://manual.seafile.com/config/seahub_settings_py/)

**Comment by noave** [comment]
because the guide is broken and has been remove anyway I will close this here https://github.com/Uberspace/lab/commit/a2e32055a0892237db99aff20fdf94f6458e9cea
