### ISSUE TITLE
logo overlaps content, if first paragraph is too short

### ISSUE THREAD

**Issue by luto** [Uberspace/lab#89]
![image](https://user-images.githubusercontent.com/2158203/39085683-a295ba66-4586-11e8-83af-40562dc0df12.png)

See https://github.com/Uberspace/lab/pull/86, https://github.com/Uberspace/lab/commit/cb4a88064d8cba553de50c7cc697e9d6aeee4168

**Comment by nichtmax** [comment]
Does not seem to work. Did you check before merging @SalocinHB?

**Comment by SalocinHB** [comment]
Of course. Works fine here.

**Comment by nichtmax** [comment]
@brutus Seems to work only sometimes, sometimes after a reload the Script does not work anymore.
![pasted_image_at_2018_05_03_02_55_pm](https://user-images.githubusercontent.com/988418/39577857-bf503054-4ee2-11e8-877e-42bbcd58dcb5.png)

**Comment by brutus** [comment]
Works here too… but I can make it bail, if I force reload the site (CTRL+SHIFT+R). After a _normal_ reload (CTRL+R) it works again :man_shrugging:

**Comment by nichtmax** [comment]
Other way around here with Safari 😁

**Comment by nichtmax** [comment]
fixed 💪
