### ISSUE TITLE
Commento no longer freely available

### ISSUE THREAD

**Issue by 2martens** [Uberspace/lab#903]
The guide for Commento no longer works. The docs aren't available anymore. Apparently, you need to pay for the service now and the release file linked in the guide isn't available anymore, either.

**Comment by EV21** [comment]
Hi  @2martens ,
**Commento is licensed with MIT, so it is actually (free) open source.**

The guide is missing some information and needs some rework.

The company behind commento is hosting a paid cloud service. - The guide don't use it here!

Self-hosting is totally free.

The guide says:

> ! Warning
> Check the [releases](https://docs.commento.io/getting-started/self-hosting/releases.html) page before you continue.

The guide was written some time ago so the download links are almost never up to date. 
This would be the latest link in this point of time.
https://dl.commento.io/release/commento-v1.8.0-linux-glibc-amd64.tar.gz

The download links have been changed.
Packages with binaries are only available for the latest release.

> The docs aren't available anymore.

I can see the docs, maybe the servers got some hiccups when you were visiting them: 
https://docs.commento.io/getting-started/self-hosting/releases.html
https://docs.commento.io/installation/self-hosting/on-your-server/release-binaries.html
https://docs.commento.io/configuration/backend/

I did **not** yet test this guide or the software, but I think it should work as before.
quick-review: It looks like you actually don't need the startup script. You can also set the environment variables for the configuration in the `~/etc/services.d/commento.ini` as many other lab guides do. - Of course you need to adapt the parameters to your setup (domain and database credentials). Maybe you don't even need to set the port - the default 8080 might also work
```ini
[program:commento]
environment=
 COMMENTO_ORIGIN="https://isabell.uber.space",
 COMMENTO_PORT="31380",
 COMMENTO_BIND_ADDRESS="0.0.0.0",
 COMMENTO_POSTGRES=postgres://<username>:<password>@<host>:<port>/<database>?sslmode=disable
directory=%(ENV_HOME)s/commento
command=commento
autostart=yes
autorestart=yes
```

**Comment by 2martens** [comment]
Thanks, the docs seem to work again.
