### ISSUE TITLE
Move from `master` to `main` breaks GitHub links

### ISSUE THREAD

**Issue by fm** [Uberspace/lab#908]
The move from `master` to `main` breaks the `Edit on GitHub` and `View Changelog` GitHub links. 
The `Edit` link currently redirects to the new URL, but the `Changelog` link returns a 404. 

<img width="750" alt="Screen Shot 2021-01-17 at 8 03 16 PM" src="https://user-images.githubusercontent.com/3654256/104861741-0b095d80-58ff-11eb-8899-e0ea5c847ada.png">

The template needs to reflect the new URL scheme from `master` to `main`

Sample old links: 
https://github.com/Uberspace/lab/blob/master/source/guide_ioncube.rst
https://github.com/Uberspace/lab/commits/master/source/guide_ioncube.rst

Would need to turn into:
https://github.com/Uberspace/lab/blob/main/source/guide_ioncube.rst
https://github.com/Uberspace/lab/commits/main/source/guide_ioncube.rst

I took a look at the [/source/_templates/breadcrumbs.html](https://github.com/Uberspace/lab/blob/main/source/_templates/breadcrumbs.html) file, but couldn't figure out which variable controlled it.

**Comment by fm** [comment]
This looks like the extended fall out mentioned in #907

**Comment by luto** [comment]
this one: [`conf.py#L127`](https://github.com/Uberspace/lab/blob/main/source/conf.py#L127).

Thanks! fixed. 92d827b1bddbd7ea9af92f06a58cd41a348cb949
