### ISSUE TITLE
[grocy] instructions not working

### ISSUE THREAD

**Issue by fosBHY** [Uberspace/lab#948]
I followed the instructions for the grocy tutorial.
The only difference is I'm not using webroot html but subdomain in /var/www/virtual/$USER/grocy.subdomain.blabla

Up came error 500.

turned off 500 by uberspace, turned on logging php and apache.
 apache log says:

`[Tue Mar 02 17:16:27 2021] [error] [pid 28021] core.c(3879): [client 185.213.0.0] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
`
subdomain is configured correctly - index.html with gibberish instead of index.php of grocy displays 'gibberish'

**Comment by jonmz** [comment]
Please note that all the guides are expected to be applied to the real DocumentRoot `html`. We don't test them using additional DocumentRoots, and we don't support them as the side effects of using additional DocumentRoots can be cumbersome.

That being said, did you take a look at https://manual.uberspace.de/web-documentroot/#additional-documentroots and took note of the hint that using RewriteRules in `.htaccess` files (the error message presented indicates that RewriteRules are in use here) might need an additional `RewriteBase /` when using additional DocumentRoots? This is never needed using the real DocumentRoot, but it might be needed when using additional ones. Could you please try that?

For now I am closing this bug report as we are only able to check back on bugs that occur when you are - exactly - following the instructions. If you do things differently - and you are definitely allowed to do so! - you might have to adapt other things as well which are not covered by the lab guide, but we regard those things as being out of scope for lab guides.

If the error also appears using the real DocumentRoot at `html` feel free to reopen this issue! Thanks for getting involved with this! <3

**Comment by fosBHY** [comment]
thank you a lot for the quick response and also the help within. This did actually work. As I'm still not experienced enough I did not find this, so thanks for the hint.

I think I have seen other lab guides which offer additional information for this kind of scenario. so this might be, even though discouraged, still be valuable help in the documentation.
