### ISSUE TITLE
redis guide issue: Save not possible

### ISSUE THREAD

**Issue by schoeke** [Uberspace/lab#953]
@SalocinHB I encountered this issue when trying to install Redis for nextcloud. I started getting `500`s . The nextcloud log contains this message repeatedly:

```
: "RedisException",
    "Message": "MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are
disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the
Redis logs for details about the RDB error.
```

I do not have access to the redis logs under `/var/log/redis` but it seems to indicate, that it can't write to the file. I can replicate the error in the redis client.

Not sure if this is a config issue on my side or on the server side.

**Comment by riweckr** [comment]
Redis tries to write to the default path where your user has no permission.

add

> `dir /home/<user>/.redis`

to your `~/.redis/conf`

**Comment by SalocinHB** [comment]
@schoeke it sounds like something's wrong in your config. Please contact Uberspace support at hallo@uberspace.de.

**Comment by schoeke** [comment]
Das Problem kann wie von @riweckr beschrieben geloest werden und das Lab ist falsch. Ich mach nen PR dafuer auf.
