### ISSUE TITLE
think about incentives

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/lab#98]
Our awesome users should get rewarded for participation. Think about incentives for:
 - New guides
 - Fixing bugs in guides

**Comment by tobidope** [comment]
If you ask me

- stickers
- free uberspace month

come to my mind

**Comment by nichtmax** [comment]
@tobidope Everybody can oder stickers: https://sticker.uberspace.de
A free month would equal 1€, that's not that much :D 

We'll go with mugs.
