### ISSUE TITLE
[nextcloud] PHP Fatal error when updating to 21.0.1

### ISSUE THREAD

**Issue by thisven** [Uberspace/lab#989]
When updating to Nextcloud 21.0.1 with `~/bin/nextcloud-update`, several occ commands fail:

> PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/virtual/isabell/html/lib/private/AppFramework/Utility/SimpleContainer.php on line 133

A work around on Uberspace is to use `--define apc.enable_cli=1` with `php` commands as [@nextcloud486153](https://github.com/nextcloud486153) mentioned in [#25742](https://github.com/nextcloud/server/issues/25742), e.g.:
`php --define apc.enable_cli=1 ~/html/occ maintenance:mode --on`

**Comment by zweiron** [comment]
I added `apc.enabled_cli=1` to a file `~/etc/php.d/apcu.ini` to resolve this issue.
This should be added to the "APCu caching" section.

The missing configuration can also cause the defined cron process to fail. This uses the occ command too.

**Comment by GodMod** [comment]
Thanks for the Workaround, my update of NC also failed with the same error.

**Comment by thisven** [comment]
> I added `apc.enabled_cli=1` to a file `~/etc/php.d/apcu.ini` to resolve this issue.

This doesn't work for me. I reloaded php configuration by `uberspace tools restart php` after creating this file, but the errors persists.

**Comment by zweiron** [comment]
There was a typo. It is `apc.enable_cli=1`. This works for me. I corrected it in the original comment.

**Comment by thisven** [comment]
Ok, now it works. Good job. =)

**Comment by luto** [comment]
https://github.com/Uberspace/lab/commit/c8ad4ee27f40a721397d31c09de3e9567f364b96
