### ISSUE TITLE
[Multidomain] Writing guide for Multidomain

### ISSUE THREAD

**Issue by groetzner-net** [Uberspace/lab#991]
I'm writing a guide to get a multidomain setup with one DocumentRoot with ModRewrite working on uberspace.
It's almost done already, but there are some descriptions to be finalized.
It`s my first guide here, so be tolerant, please.

**Comment by luto** [comment]
Do you have link to the project? Are you referring to WordPress Multisite?

**Comment by groetzner-net** [comment]
Sorry no project, it is universal.
One Account with:
-example1.com -> Project 1 (static website)
-example2.com -> Project 2 (Application 1)
-example3.com -> Project 3 (Application 2)
The guild is almost ready...

**Comment by luto** [comment]
https://github.com/Uberspace/lab/pull/993#issuecomment-818031492 - this functionality is already built into uberspace 7, so there is no need for a guide.
